#!/usr/bin/env bash
#
# Mirror the CqrsDsl sources (hand-written AND generated) from the Eclipse plugin into the Maven
# module. Each is a true mirror (rsync --delete): files added/changed on the Eclipse side are copied
# over, files removed there are removed from the Maven side.
#
#   eclipse/org.fuin.dsl.cqrs/src/org        ->  maven/org.fuin.dsl.cqrs/src/main/java/org
#   eclipse/org.fuin.dsl.cqrs/src-gen/org    ->  maven/org.fuin.dsl.cqrs/src/main/xtext-gen/org
#   eclipse/org.fuin.dsl.cqrs/xtend-gen/org  ->  maven/org.fuin.dsl.cqrs/src/main/xtend-gen/org
#
# Maven-specific files are excluded so the mirror neither overwrites nor deletes them (rsync also
# protects excluded paths from --delete):
#
#   * GenerateCqrsDsl.mwe2          - the Maven module uses its own workflow (mavenLayout = true and
#                                     an explicit composedCheck), different from the Eclipse one.
#   * AbstractCqrsDslValidator.java - generated from that workflow with @ComposedChecks, so the
#                                     Maven variant must be kept (it is regenerated by the build).
#   * *.xtendbin / *._trace         - Eclipse-only Xtend build artifacts (gitignored); the Maven
#                                     Xtend plugin does not produce .xtendbin files.
#
# Usage:
#   ./mirror-eclipse-sources-to-maven.sh          # perform the mirror
#   ./mirror-eclipse-sources-to-maven.sh -n       # dry run: show what would change, do nothing
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ECL="$ROOT_DIR/eclipse/org.fuin.dsl.cqrs"
MVN="$ROOT_DIR/maven/org.fuin.dsl.cqrs"

DRY_RUN=()
case "${1:-}" in
	-n|--dry-run) DRY_RUN=(--dry-run); echo "DRY RUN — no files will be changed." ;;
	"") ;;
	*) echo "Usage: $(basename "$0") [-n|--dry-run]" >&2; exit 2 ;;
esac

# mirror <label> <src-dir> <dst-dir> [extra rsync args...]
mirror() {
	local label="$1" src="$2" dst="$3"
	shift 3
	[ -d "$src" ] || { echo "ERROR: source not found: $src" >&2; exit 1; }
	mkdir -p "$dst"
	echo "==> $label"
	# --checksum: compare by content, not size+mtime, so the mirror is idempotent and is not
	#   disturbed by the differing generation timestamps of the Eclipse vs Maven builds.
	# --no-times / --omit-dir-times: don't copy mtimes (irrelevant for source under git, and Maven
	#   regenerates anyway) so unchanged files are skipped silently and only real changes are listed.
	rsync -a --no-times --omit-dir-times --delete --checksum --itemize-changes \
		"${DRY_RUN[@]}" "$@" "$src/" "$dst/"
}

# 1. Hand-written sources.
mirror "src -> src/main/java" \
	"$ECL/src/org" "$MVN/src/main/java/org" \
	--exclude="/fuin/dsl/cqrs/GenerateCqrsDsl.mwe2"

# 2. Xtext-generated sources (EMF model, ANTLR parser, infrastructure).
mirror "src-gen -> src/main/xtext-gen" \
	"$ECL/src-gen/org" "$MVN/src/main/xtext-gen/org" \
	--exclude="/fuin/dsl/cqrs/validation/AbstractCqrsDslValidator.java"

# 3. Xtend-compiled sources (skip Eclipse-only build artifacts).
mirror "xtend-gen -> src/main/xtend-gen" \
	"$ECL/xtend-gen/org" "$MVN/src/main/xtend-gen/org" \
	--exclude="*.xtendbin" --exclude="*._trace"

echo "Mirrored eclipse -> maven (Maven-specific files left untouched)."
