/*
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.fuin.dsl.cqrs.ui.internal.CqrsActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CqrsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CqrsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CqrsActivator activator = CqrsActivator.getInstance();
		return activator != null ? activator.getInjector(CqrsActivator.ORG_FUIN_DSL_CQRS_CQRSDSL) : null;
	}

}
