/**
 * generated by Xtext 2.39.0
 */
package org.fuin.dsl.cqrs.validation;

import com.google.common.collect.Iterables;
import com.google.inject.Inject;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.IContainer;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.resource.IResourceDescriptions;
import org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.Pair;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.fuin.dsl.cqrs.analysis.CqrsModuleDependencies;
import org.fuin.dsl.cqrs.cqrsDsl.AbstractElement;
import org.fuin.dsl.cqrs.cqrsDsl.AbstractEntity;
import org.fuin.dsl.cqrs.cqrsDsl.AbstractEntityId;
import org.fuin.dsl.cqrs.cqrsDsl.AbstractMethod;
import org.fuin.dsl.cqrs.cqrsDsl.Aggregate;
import org.fuin.dsl.cqrs.cqrsDsl.AggregateId;
import org.fuin.dsl.cqrs.cqrsDsl.AnnotationInstance;
import org.fuin.dsl.cqrs.cqrsDsl.Attribute;
import org.fuin.dsl.cqrs.cqrsDsl.BusinessRule;
import org.fuin.dsl.cqrs.cqrsDsl.BusinessRuleInstance;
import org.fuin.dsl.cqrs.cqrsDsl.CarrierAttributeArgument;
import org.fuin.dsl.cqrs.cqrsDsl.Command;
import org.fuin.dsl.cqrs.cqrsDsl.Consistency;
import org.fuin.dsl.cqrs.cqrsDsl.ConsistencyLevel;
import org.fuin.dsl.cqrs.cqrsDsl.Constraint;
import org.fuin.dsl.cqrs.cqrsDsl.ConstraintInstance;
import org.fuin.dsl.cqrs.cqrsDsl.Constructor;
import org.fuin.dsl.cqrs.cqrsDsl.Context;
import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.Dependency;
import org.fuin.dsl.cqrs.cqrsDsl.Entity;
import org.fuin.dsl.cqrs.cqrsDsl.EntityId;
import org.fuin.dsl.cqrs.cqrsDsl.EntityIdPathType;
import org.fuin.dsl.cqrs.cqrsDsl.Event;
import org.fuin.dsl.cqrs.cqrsDsl.ExternalType;
import org.fuin.dsl.cqrs.cqrsDsl.GenericArgs;
import org.fuin.dsl.cqrs.cqrsDsl.Hint;
import org.fuin.dsl.cqrs.cqrsDsl.IdentityArgument;
import org.fuin.dsl.cqrs.cqrsDsl.Import;
import org.fuin.dsl.cqrs.cqrsDsl.InternalType;
import org.fuin.dsl.cqrs.cqrsDsl.Literal;
import org.fuin.dsl.cqrs.cqrsDsl.Method;
import org.fuin.dsl.cqrs.cqrsDsl.Parameter;
import org.fuin.dsl.cqrs.cqrsDsl.PathSegment;
import org.fuin.dsl.cqrs.cqrsDsl.ProcessManager;
import org.fuin.dsl.cqrs.cqrsDsl.ProcessReaction;
import org.fuin.dsl.cqrs.cqrsDsl.ProcessState;
import org.fuin.dsl.cqrs.cqrsDsl.ReturnType;
import org.fuin.dsl.cqrs.cqrsDsl.RuleArgument;
import org.fuin.dsl.cqrs.cqrsDsl.RuleAttrRef;
import org.fuin.dsl.cqrs.cqrsDsl.RuleComparison;
import org.fuin.dsl.cqrs.cqrsDsl.RuleOperand;
import org.fuin.dsl.cqrs.cqrsDsl.RuleRefOperand;
import org.fuin.dsl.cqrs.cqrsDsl.SegmentRange;
import org.fuin.dsl.cqrs.cqrsDsl.Service;
import org.fuin.dsl.cqrs.cqrsDsl.Type;
import org.fuin.dsl.cqrs.cqrsDsl.ValueObject;
import org.fuin.dsl.cqrs.cqrsDsl.Variable;
import org.fuin.dsl.cqrs.cqrsDsl.View;
import org.fuin.dsl.cqrs.extensions.CqrsAbstractElementExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsAbstractEntityExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsAbstractVOExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsAggregateExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsAttributeExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsBusinessRulesExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsCollectionExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsConstraintExtension;
import org.fuin.dsl.cqrs.extensions.CqrsEObjectExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsEntityExtensions;
import org.fuin.dsl.cqrs.extensions.CqrsParameterExtensions;
import org.fuin.dsl.cqrs.scoping.CqrsDependencies;
import org.fuin.dsl.cqrs.scoping.CqrsModelArchives;
import org.fuin.dsl.cqrs.scoping.RemoteScopeEntry;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CqrsDslValidator extends AbstractCqrsDslValidator {
  private static final String MSG_DIRECT_REF_AGGREGATE = "A direct reference to an aggregate is only allowed from entities in the same aggregate";

  private static final String MSG_DIRECT_REF_ENTITY = "A direct reference to an entity is only allowed from entities in the same aggregate";

  public static final String INVALID_VAR_NAME = "invalidVarName";

  public static final String EVENT_ONLY_ALLOWED_FOR_ENTITY = "eventOnlyAllowedForEntity";

  public static final String CONSTRAINT_MSG_UNKNOWN_VAR = "constraintMsgUnknownVar";

  public static final String EXCEPTION_MSG_UNKNOWN_VAR = "exceptionMsgUnknownVar";

  public static final String PROCESS_STATE_DUPLICATE = "processStateDuplicate";

  public static final String PROCESS_CORRELATION_KEY_UNKNOWN = "processCorrelationKeyUnknown";

  public static final String REF_TO_AGGREGATE_NOT_ALLOWED = "refToAggregateNotAllowed";

  public static final String REF_TO_ENTITY_NOT_ALLOWED = "refToEntityNotAllowed";

  public static final String MISSING_DOC = "missingDOC";

  public static final String EVENT_MSG_UNKNOWN_VAR = "eventMsgUnknownVar";

  public static final String COMMAND_MSG_UNKNOWN_VAR = "commandMsgUnknownVar";

  public static final String COMMAND_MSG_NOT_A_PATH = "commandMsgNotAPath";

  public static final String COMMAND_MSG_UNCLOSED_VAR = "commandMsgUnclosedVar";

  public static final String RULE_OWN_ID_IN_CONSTRUCTOR = "ruleOwnIdInConstructor";

  public static final String RULE_OWN_ATTRIBUTE_IN_CONSTRUCTOR = "ruleOwnAttributeInConstructor";

  public static final String RULE_EXCEPTION_NOT_SUPPLIED = "ruleExceptionNotSupplied";

  public static final String RULE_ACTUALS_MISMATCH = "ruleActualsMismatch";

  public static final String RULE_COMPARISON_TYPE_MISMATCH = "ruleComparisonTypeMismatch";

  public static final String EXCEPTION_DUPLICATE_CID = "exceptionDuplicateCID";

  public static final String DEPENDENCY_INVALID_COORDINATE = "dependencyInvalidCoordinate";

  public static final String DEPENDENCY_DUPLICATE = "dependencyDuplicate";

  public static final String DEPENDENCY_UNRESOLVED = "dependencyUnresolved";

  public static final String IMPORT_UNRESOLVED = "importUnresolved";

  public static final String IMPORT_DUPLICATE = "importDuplicate";

  public static final String IMPORT_UNUSED = "importUnused";

  public static final String MODULE_DEPENDENCY_CYCLE = "moduleDependencyCycle";

  public static final String ROW_CANNOT_ANSWER_GATE = "rowCannotAnswerGate";

  public static final String PATH_NEEDS_MORE_THAN_A_ROOT = "pathNeedsMoreThanARoot";

  public static final String PATH_MUST_START_AT_A_ROOT = "pathMustStartAtARoot";

  public static final String PATH_SEGMENT_NOT_OF_ROOT = "pathSegmentNotOfRoot";

  public static final String PATH_RANGE_INVALID = "pathRangeInvalid";

  public static final String SERVICE_METHOD_CANNOT_FIRE_EVENTS = "serviceMethodCannotFireEvents";

  public static final String SERVICE_METHOD_CANNOT_DECLARE_EVENTS = "serviceMethodCannotDeclareEvents";

  public static final String REST_PATH_ONLY_ON_VIEW_METHODS = "restPathOnlyOnViewMethods";

  public static final String REST_PATH_UNKNOWN_VAR = "restPathUnknownVar";

  public static final String BUSINESS_RULE_REQUIRES_EXCEPTION = "businessRuleRequiresException";

  public static final String BUSINESS_RULE_REQUIRES_CONSISTENCY = "businessRuleRequiresConsistency";

  public static final String ATTRIBUTE_INVARIANT_WRONG_TARGET_TYPE = "attributeInvariantWrongTargetType";

  public static final String PARAMETER_CONSTRAINT_WRONG_TARGET_TYPE = "parameterConstraintWrongTargetType";

  public static final String INTERNAL_TYPE_INVARIANT_WRONG_TARGET_TYPE = "internalTypeInvariantWrongTargetType";

  public static final String WEAK_CONSISTENCY_REQUIRES_DETAILS = "weakConsistencyRequiresDetails";

  public static final String STRONG_CONSISTENCY_DOES_NOT_ALLOW_DETAILS = "strongConsistencyDoesNotAllowDetails";

  public static final String WRONG_IDENTIFIES_AGGREGATE = "wrongIdentifiesAggregate";

  public static final String IDENTIFIES_AGGREGATE_NULL = "identifiesAggregateNull";

  public static final String WRONG_IDENTIFIES_ENTITY = "wrongIdentifiesEntity";

  public static final String IDENTIFIES_ENTITY_NULL = "identifiesEntityNull";

  public static final String WRONG_ROOT_AGGREGATE = "wrongRootAggregate";

  public static final String ROOT_NULL = "rootNull";

  public static final String AGGREGATE_WITHOUT_ID = "aggregateWithoutId";

  public static final String AGGREGATE_WITH_DUPLICATE_ID = "aggregateWithDuplicateId";

  public static final String ENTITY_WITHOUT_ID = "entityWithoutId";

  public static final String ENTITY_WITH_DUPLICATE_ID = "entityWithDuplicateId";

  public static final String ILLEGAL_AGGREGATE_ELEMENT = "illegalAggregateElement";

  public static final String ILLEGAL_ENTITY_ELEMENT = "illegalEntityElement";

  public static final String MULTIPLE_AGGREGATE_ID_ELEMENTS = "multipleAggregateIdElements";

  public static final String MULTIPLE_ENTITY_ID_ELEMENTS = "multipleEntityIdElements";

  public static final String VAR_GENERICS_COUNT_MISMATCH = "varGenericsCountMismatch";

  public static final String RETURN_TYPE_GENERICS_COUNT_MISMATCH = "returnTypeGenericsCountMismatch";

  public static final String ANNOTATION_PARAM_COUNT_MISMATCH = "annotationParamCountMismatch";

  public static final String VALUE_OBJECT_BASE_NO_CONSTRUCTORS_OR_METHODS = "valueObjectBaseNoConstructorsOrMethods";

  public static final String INVALID_CRON_EXPRESSION = "invalidCronExpression";

  public static final String HINT_JSON_SCHEMA_VIOLATION = "hintJsonSchemaViolation";

  public static final String JPA_HINT_OUTSIDE_VIEW = "jpaHintOutsideView";

  @Inject
  private IContainer.Manager containerManager;

  @Inject
  private ResourceDescriptionsProvider resourceDescriptionsProvider;

  @Inject
  private IQualifiedNameProvider qualifiedNameProvider;

  @Inject
  private CqrsDependencies dependencies;

  @Check
  public void checkNameStartsWithCapital(final Variable variable) {
    boolean _isLowerCase = Character.isLowerCase(variable.getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Variable names should start with a lower case", variable, 
        CqrsDslPackage.Literals.VARIABLE__NAME, CqrsDslValidator.INVALID_VAR_NAME);
    }
  }

  /**
   * A dependency coordinate must be a Maven GAV: "groupId:artifactId:version".
   */
  @Check
  public void checkDependencyCoordinate(final Dependency dependency) {
    RemoteScopeEntry _parse = RemoteScopeEntry.parse(dependency.getCoordinate(), dependency.getLocal());
    boolean _tripleEquals = (_parse == null);
    if (_tripleEquals) {
      String _coordinate = dependency.getCoordinate();
      String _plus = ("A dependency must be \'groupId:artifactId:version\', but was \'" + _coordinate);
      String _plus_1 = (_plus + "\'");
      this.error(_plus_1, dependency, 
        CqrsDslPackage.Literals.DEPENDENCY__COORDINATE, 
        CqrsDslValidator.DEPENDENCY_INVALID_COORDINATE);
    }
  }

  /**
   * A well formed coordinate must also resolve to something. Without this the only symptom of a
   * missing artifact is every type it provides failing to resolve, which points at the models
   * instead of at the declaration that is actually wrong.
   */
  @Check
  public void checkDependencyResolves(final Dependency dependency) {
    final String problem = this.dependencies.resolutionProblem(dependency);
    if ((problem != null)) {
      String _coordinate = dependency.getCoordinate();
      String _plus = ("Cannot resolve dependency \'" + _coordinate);
      String _plus_1 = (_plus + "\': ");
      String _plus_2 = (_plus_1 + problem);
      this.error(_plus_2, dependency, 
        CqrsDslPackage.Literals.DEPENDENCY__COORDINATE, 
        CqrsDslValidator.DEPENDENCY_UNRESOLVED);
    }
  }

  /**
   * The same artifact must not be declared twice in one block, nor repeated on a module that
   * already inherits it from its context.
   */
  @Check
  public void checkDuplicateDependency(final Dependency dependency) {
    final String coordinate = dependency.getCoordinate();
    if ((coordinate == null)) {
      return;
    }
    final EObject container = dependency.eContainer();
    EList<Dependency> _switchResult = null;
    boolean _matched = false;
    if (container instanceof Context) {
      _matched=true;
      _switchResult = ((Context)container).getDependencies();
    }
    if (!_matched) {
      if (container instanceof org.fuin.dsl.cqrs.cqrsDsl.Module) {
        _matched=true;
        _switchResult = ((org.fuin.dsl.cqrs.cqrsDsl.Module)container).getDependencies();
      }
    }
    if (!_matched) {
      _switchResult = null;
    }
    final EList<Dependency> siblings = _switchResult;
    if ((siblings == null)) {
      return;
    }
    if (((IterableExtensions.size(IterableExtensions.<Dependency>filter(siblings, ((Function1<Dependency, Boolean>) (Dependency it) -> {
      String _coordinate = it.getCoordinate();
      return Boolean.valueOf(Objects.equals(_coordinate, coordinate));
    }))) > 1) && (IterableExtensions.<Dependency>findFirst(siblings, ((Function1<Dependency, Boolean>) (Dependency it) -> {
      String _coordinate = it.getCoordinate();
      return Boolean.valueOf(Objects.equals(_coordinate, coordinate));
    })) != dependency))) {
      this.error((("Duplicate dependency \'" + coordinate) + "\'"), dependency, 
        CqrsDslPackage.Literals.DEPENDENCY__COORDINATE, CqrsDslValidator.DEPENDENCY_DUPLICATE);
      return;
    }
    if ((container instanceof org.fuin.dsl.cqrs.cqrsDsl.Module)) {
      final EObject context = ((org.fuin.dsl.cqrs.cqrsDsl.Module)container).eContainer();
      if ((context instanceof Context)) {
        final Function1<Dependency, Boolean> _function = (Dependency it) -> {
          String _coordinate = it.getCoordinate();
          return Boolean.valueOf(Objects.equals(_coordinate, coordinate));
        };
        boolean _exists = IterableExtensions.<Dependency>exists(((Context)context).getDependencies(), _function);
        if (_exists) {
          String _name = ((Context)context).getName();
          String _plus = ((("Dependency \'" + coordinate) + "\' is already declared by context \'") + _name);
          String _plus_1 = (_plus + "\'");
          this.warning(_plus_1, dependency, CqrsDslPackage.Literals.DEPENDENCY__COORDINATE, CqrsDslValidator.DEPENDENCY_DUPLICATE);
        }
      }
    }
  }

  /**
   * An import must address something that exists: a context, a module or a single type. Anything
   * else is a typo that would silently leave every name it was meant to provide unresolved.
   */
  @Check
  public void checkImportResolves(final Import imp) {
    final String imported = imp.getImportedNamespace();
    boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(imported);
    if (_isNullOrEmpty) {
      return;
    }
    boolean _importMatchesAnything = this.importMatchesAnything(imp, imported);
    boolean _not = (!_importMatchesAnything);
    if (_not) {
      this.error((("Import \'" + imported) + "\' does not match any context, module or type"), imp, 
        CqrsDslPackage.Literals.IMPORT__IMPORTED_NAMESPACE, CqrsDslValidator.IMPORT_UNRESOLVED);
    }
  }

  /**
   * The same name must not be imported twice in one block, nor repeated on a module that already
   * inherits it from its context.
   */
  @Check
  public void checkDuplicateImport(final Import imp) {
    final String imported = imp.getImportedNamespace();
    boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(imported);
    if (_isNullOrEmpty) {
      return;
    }
    final EObject container = imp.eContainer();
    EList<Import> _switchResult = null;
    boolean _matched = false;
    if (container instanceof Context) {
      _matched=true;
      _switchResult = ((Context)container).getImports();
    }
    if (!_matched) {
      if (container instanceof org.fuin.dsl.cqrs.cqrsDsl.Module) {
        _matched=true;
        _switchResult = ((org.fuin.dsl.cqrs.cqrsDsl.Module)container).getImports();
      }
    }
    if (!_matched) {
      _switchResult = null;
    }
    final EList<Import> siblings = _switchResult;
    if ((siblings == null)) {
      return;
    }
    if (((IterableExtensions.size(IterableExtensions.<Import>filter(siblings, ((Function1<Import, Boolean>) (Import it) -> {
      String _importedNamespace = it.getImportedNamespace();
      return Boolean.valueOf(Objects.equals(_importedNamespace, imported));
    }))) > 1) && 
      (IterableExtensions.<Import>findFirst(siblings, ((Function1<Import, Boolean>) (Import it) -> {
        String _importedNamespace = it.getImportedNamespace();
        return Boolean.valueOf(Objects.equals(_importedNamespace, imported));
      })) != imp))) {
      this.error((("Duplicate import \'" + imported) + "\'"), imp, 
        CqrsDslPackage.Literals.IMPORT__IMPORTED_NAMESPACE, CqrsDslValidator.IMPORT_DUPLICATE);
      return;
    }
    if ((container instanceof org.fuin.dsl.cqrs.cqrsDsl.Module)) {
      final EObject context = ((org.fuin.dsl.cqrs.cqrsDsl.Module)container).eContainer();
      if ((context instanceof Context)) {
        final Function1<Import, Boolean> _function = (Import it) -> {
          String _importedNamespace = it.getImportedNamespace();
          return Boolean.valueOf(Objects.equals(_importedNamespace, imported));
        };
        boolean _exists = IterableExtensions.<Import>exists(((Context)context).getImports(), _function);
        if (_exists) {
          String _name = ((Context)context).getName();
          String _plus = ((("Import \'" + imported) + "\' is already declared by context \'") + _name);
          String _plus_1 = (_plus + "\'");
          this.warning(_plus_1, imp, CqrsDslPackage.Literals.IMPORT__IMPORTED_NAMESPACE, CqrsDslValidator.IMPORT_DUPLICATE);
        }
      }
    }
  }

  /**
   * An import nothing in the block refers to is dead weight and hides the real coupling.
   */
  @Check
  public void checkUnusedImport(final Import imp) {
    final String imported = imp.getImportedNamespace();
    boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(imported);
    if (_isNullOrEmpty) {
      return;
    }
    final EObject container = imp.eContainer();
    if ((container == null)) {
      return;
    }
    boolean _importMatchesAnything = this.importMatchesAnything(imp, imported);
    boolean _not = (!_importMatchesAnything);
    if (_not) {
      return;
    }
    final Function1<String, Boolean> _function = (String it) -> {
      return Boolean.valueOf(this.covers(imported, it));
    };
    boolean _exists = IterableExtensions.<String>exists(this.referencedNames(container), _function);
    if (_exists) {
      return;
    }
    boolean _hasUnresolvedReference = this.hasUnresolvedReference(container);
    if (_hasUnresolvedReference) {
      return;
    }
    this.warning((("Import \'" + imported) + "\' is not used"), imp, 
      CqrsDslPackage.Literals.IMPORT__IMPORTED_NAMESPACE, CqrsDslValidator.IMPORT_UNUSED);
  }

  /**
   * Reports a module that takes part in a dependency cycle.
   * 
   * <p>A cycle means neither module can be reasoned about - or switched off - without the other, and
   * the generated module dependency graph would have no topological order to offer a consumer. It is
   * an error rather than a warning because there is no version of it that is intended.</p>
   * 
   * <p><b>A module, not a bounded context.</b> The nodes are the {@code module} blocks as declared,
   * so a view or a process manager is a node of its own. That granularity is what keeps the seams
   * between contexts legal: a process manager may react to another context's events while the
   * context it lives beside stays independent of it. Rolling the sub-modules up into their context
   * is a question a consumer of the generated graph can ask; it is not what this rule enforces.</p>
   * 
   * <p><b>The build is the enforcement point.</b> SrcGen4J parses the whole model into one resource
   * set, so a build sees every module and every edge. An editor validates one resource and reaches
   * the rest only through the index, so a cycle closed by a file that is not open may surface late
   * or not at all. That is a deliberate trade: no editor-side index walk on every keystroke, and the
   * build refuses regardless.</p>
   */
  @Check
  public void checkModuleDependencyCycle(final org.fuin.dsl.cqrs.cqrsDsl.Module module) {
    Resource _eResource = module.eResource();
    URI _uRI = null;
    if (_eResource!=null) {
      _uRI=_eResource.getURI();
    }
    boolean _isArchived = CqrsModelArchives.isArchived(_uRI);
    if (_isArchived) {
      return;
    }
    Resource _eResource_1 = module.eResource();
    ResourceSet _resourceSet = null;
    if (_eResource_1!=null) {
      _resourceSet=_eResource_1.getResourceSet();
    }
    final Map<String, Set<String>> graph = CqrsModuleDependencies.graphOf(_resourceSet);
    final List<String> cycle = CqrsModuleDependencies.cycleThrough(module.getName(), graph);
    boolean _isEmpty = cycle.isEmpty();
    if (_isEmpty) {
      return;
    }
    String _name = module.getName();
    String _plus = ("Module \'" + _name);
    String _plus_1 = (_plus + "\' is part of a dependency cycle: ");
    String _join = IterableExtensions.join(cycle, " -> ");
    String _plus_2 = (_plus_1 + _join);
    this.error(_plus_2, module, CqrsDslPackage.Literals.MODULE__NAME, CqrsDslValidator.MODULE_DEPENDENCY_CYCLE);
  }

  /**
   * Whether anything inside the given block points at something that could not be resolved. Only
   * asked when an import is about to be reported as unused, which is rare enough for a second walk.
   */
  private boolean hasUnresolvedReference(final EObject container) {
    final TreeIterator<EObject> contents = container.eAllContents();
    while (contents.hasNext()) {
      {
        final EObject obj = contents.next();
        final Function1<EReference, Boolean> _function = (EReference it) -> {
          return Boolean.valueOf(((!it.isContainment()) && (!it.isDerived())));
        };
        Iterable<EReference> _filter = IterableExtensions.<EReference>filter(obj.eClass().getEAllReferences(), _function);
        for (final EReference reference : _filter) {
          {
            final Object value = obj.eGet(reference, false);
            List<?> _xifexpression = null;
            boolean _isMany = reference.isMany();
            if (_isMany) {
              _xifexpression = ((List<?>) value);
            } else {
              _xifexpression = Collections.<Object>singletonList(value);
            }
            final List<?> targets = _xifexpression;
            Iterable<?> _filterNull = IterableExtensions.filterNull(targets);
            for (final Object target : _filterNull) {
              if ((target instanceof EObject)) {
                boolean _eIsProxy = ((EObject)target).eIsProxy();
                if (_eIsProxy) {
                  return true;
                }
              }
            }
          }
        }
      }
    }
    return false;
  }

  /**
   * The qualified names of everything the cross references inside the given block resolve to. A
   * context is asked for its own references and for those of all of its modules, because a context
   * level import serves them all.
   * 
   * <p>The references are <em>resolved</em> rather than read as they lie. Xtext links lazily: until
   * somebody asks for the target, the feature still holds a proxy, and a proxy would be read here as
   * "this name refers to nothing" - which turns into "the import providing it is unused". Whether the
   * editor happened to have resolved a name already, because a hover or a Ctrl-click asked for it,
   * must not decide whether its import is reported.</p>
   */
  private Iterable<String> referencedNames(final EObject container) {
    return CqrsModuleDependencies.referencedNames(container, this.qualifiedNameProvider);
  }

  /**
   * Whether an imported name covers a fully qualified name: an exact match, or - for a wildcard -
   * a name below its prefix.
   */
  private boolean covers(final String imported, final String qualifiedName) {
    boolean _endsWith = imported.endsWith(".*");
    if (_endsWith) {
      int _length = imported.length();
      int _minus = (_length - 1);
      return qualifiedName.startsWith(imported.substring(0, _minus));
    }
    return Objects.equals(imported, qualifiedName);
  }

  /**
   * Whether anything the resource can address matches the imported name: what the index holds, and
   * what the declared dependencies provide.
   * 
   * <p>The second half is not a shortcut for the first. In an IDE the index is the workspace
   * builder state, which knows the project's files and never a model read out of a dependency's
   * zip - while the scope such an import feeds does see them, through
   * {@link CqrsDslGlobalScopeProvider}. Asking both is what keeps this check from reporting an
   * import whose types resolve perfectly well. Headless the two overlap, because there the index
   * <em>is</em> the resource set the dependency models are loaded into.</p>
   */
  private boolean importMatchesAnything(final Import imp, final String imported) {
    final Resource resource = imp.eResource();
    if ((resource == null)) {
      return true;
    }
    final IResourceDescriptions resourceDescriptions = this.resourceDescriptionsProvider.getResourceDescriptions(resource);
    final IResourceDescription resourceDescription = resourceDescriptions.getResourceDescription(resource.getURI());
    if ((resourceDescription == null)) {
      return true;
    }
    List<IContainer> _visibleContainers = this.containerManager.getVisibleContainers(resourceDescription, resourceDescriptions);
    for (final IContainer container : _visibleContainers) {
      Iterable<IEObjectDescription> _exportedObjects = container.getExportedObjects();
      for (final IEObjectDescription descr : _exportedObjects) {
        {
          final QualifiedName name = descr.getName();
          if (((name != null) && this.covers(imported, name.toString()))) {
            return true;
          }
        }
      }
    }
    final Function1<QualifiedName, Boolean> _function = (QualifiedName it) -> {
      return Boolean.valueOf(this.covers(imported, it.toString()));
    };
    return IterableExtensions.<QualifiedName>exists(this.dependencies.providedNames(resource), _function);
  }

  /**
   * A model read out of a dependency's archive is not reported on. It is opened read-only, it
   * belongs to another project, and whoever authored it has validated it there - a marker on it
   * would name a problem the reader cannot fix. This mirrors what the IntelliJ plugin does for a
   * file outside the project.
   */
  @Override
  protected boolean isResponsible(final Map<Object, Object> context, final EObject eObject) {
    boolean _isResponsible = super.isResponsible(context, eObject);
    boolean _not = (!_isResponsible);
    if (_not) {
      return false;
    }
    Resource _eResource = eObject.eResource();
    URI _uRI = null;
    if (_eResource!=null) {
      _uRI=_eResource.getURI();
    }
    boolean _isArchived = CqrsModelArchives.isArchived(_uRI);
    return (!_isArchived);
  }

  @Check
  public void checkVariablesInConstraintMessage(final Constraint constraint) {
    final String name = CqrsDslValidator.findUnknownVar(CqrsAttributeExtensions.asNames(CqrsConstraintExtension.allAllowedVariables(constraint)), constraint.getMessage());
    if ((name != null)) {
      this.error(
        (("A variable with the name \'" + name) + "\' is unknown"), constraint, 
        CqrsDslPackage.Literals.CONSTRAINT__MESSAGE, 
        CqrsDslValidator.CONSTRAINT_MSG_UNKNOWN_VAR);
    }
  }

  @Check
  public void checkVariablesInExceptionMessage(final org.fuin.dsl.cqrs.cqrsDsl.Exception ex) {
    final String name = CqrsDslValidator.findUnknownVar(CqrsAttributeExtensions.asNames(ex.getAttributes()), ex.getMessage());
    if ((name != null)) {
      this.error(
        (("A variable \'" + name) + "\' is not defined in the exception"), ex, 
        CqrsDslPackage.Literals.EXCEPTION__MESSAGE, 
        CqrsDslValidator.EXCEPTION_MSG_UNKNOWN_VAR);
    }
  }

  @Check
  public void checkForbiddenTypeRefs(final Variable variable) {
    Type _type = variable.getType();
    if ((_type instanceof Aggregate)) {
      Type _type_1 = variable.getType();
      final Aggregate aggregate = ((Aggregate) _type_1);
      final Entity parentEntity = CqrsEObjectExtensions.<Entity>getParent(Entity.class, variable);
      if (((parentEntity == null) || (!CqrsAbstractElementExtensions.same(aggregate, parentEntity.getRoot())))) {
        this.error(
          CqrsDslValidator.MSG_DIRECT_REF_AGGREGATE, variable, 
          CqrsDslPackage.Literals.VARIABLE__TYPE, 
          CqrsDslValidator.REF_TO_AGGREGATE_NOT_ALLOWED, 
          CqrsAggregateExtensions.getIdTypeNullsafe(aggregate).getName());
      }
    }
    Type _type_2 = variable.getType();
    if ((_type_2 instanceof Entity)) {
      Type _type_3 = variable.getType();
      final Entity entity = ((Entity) _type_3);
      final Aggregate aggregateOfVariable = CqrsEObjectExtensions.getAggregate(variable);
      if (((aggregateOfVariable == null) || (!CqrsAbstractElementExtensions.same(aggregateOfVariable, entity.getRoot())))) {
        this.error(
          CqrsDslValidator.MSG_DIRECT_REF_ENTITY, variable, 
          CqrsDslPackage.Literals.VARIABLE__TYPE, 
          CqrsDslValidator.REF_TO_ENTITY_NOT_ALLOWED, 
          CqrsEntityExtensions.getIdTypeNullsafe(entity).getName());
      }
    }
  }

  @Check
  public void checkNoRefToAggregate(final Method method) {
    Type _type = method.getReturnType().getType();
    if ((_type instanceof Aggregate)) {
      Type _type_1 = method.getReturnType().getType();
      final Aggregate aggregate = ((Aggregate) _type_1);
      final Entity parentEntity = CqrsEObjectExtensions.<Entity>getParent(Entity.class, method);
      if (((parentEntity == null) || (!CqrsAbstractElementExtensions.same(aggregate, parentEntity.getRoot())))) {
        this.error(
          CqrsDslValidator.MSG_DIRECT_REF_AGGREGATE, method, 
          CqrsDslPackage.Literals.METHOD__RETURN_TYPE, 
          CqrsDslValidator.REF_TO_AGGREGATE_NOT_ALLOWED, 
          CqrsAggregateExtensions.getIdTypeNullsafe(aggregate).getName());
      }
    } else {
      Type _type_2 = method.getReturnType().getType();
      if ((_type_2 instanceof Entity)) {
        Type _type_3 = method.getReturnType().getType();
        final Entity entity = ((Entity) _type_3);
        final Entity parentEntity_1 = CqrsEObjectExtensions.<Entity>getParent(Entity.class, method);
        if (((parentEntity_1 == null) || (!CqrsAbstractElementExtensions.same(entity.getRoot(), parentEntity_1.getRoot())))) {
          this.error(
            CqrsDslValidator.MSG_DIRECT_REF_ENTITY, method, 
            CqrsDslPackage.Literals.METHOD__RETURN_TYPE, 
            CqrsDslValidator.REF_TO_ENTITY_NOT_ALLOWED, 
            CqrsEntityExtensions.getIdTypeNullsafe(entity).getName());
        }
      }
    }
  }

  @Check
  public void checkNoEventsInService(final Method method) {
    EObject _eContainer = method.eContainer();
    if ((_eContainer instanceof Service)) {
      if (((method.getFiredEvents() != null) && (method.getFiredEvents().size() > 0))) {
        this.error(
          "A service method cannot fire events", method, 
          CqrsDslPackage.Literals.ABSTRACT_METHOD__FIRED_EVENTS, 
          CqrsDslValidator.SERVICE_METHOD_CANNOT_FIRE_EVENTS);
      }
      if (((method.getEvents() != null) && (method.getEvents().size() > 0))) {
        this.error(
          "A service method cannot declare events", method, 
          CqrsDslPackage.Literals.ABSTRACT_METHOD__EVENTS, 
          CqrsDslValidator.SERVICE_METHOD_CANNOT_DECLARE_EVENTS);
      }
    }
  }

  @Check
  public void checkMethodRestPath(final Method method) {
    String _restPath = method.getRestPath();
    boolean _tripleEquals = (_restPath == null);
    if (_tripleEquals) {
      return;
    }
    EObject _eContainer = method.eContainer();
    boolean _not = (!(_eContainer instanceof View));
    if (_not) {
      this.error(
        "A \'rest-path\' is only allowed for a view method", method, 
        CqrsDslPackage.Literals.METHOD__REST_PATH, 
        CqrsDslValidator.REST_PATH_ONLY_ON_VIEW_METHODS);
      return;
    }
    final List<String> names = CqrsParameterExtensions.asNames(method.getParameters());
    final String name = CqrsDslValidator.findUnknownPathVar(names, method.getRestPath());
    if ((name != null)) {
      this.error(
        (("A parameter with the name \'" + name) + "\' is unknown"), method, 
        CqrsDslPackage.Literals.METHOD__REST_PATH, 
        CqrsDslValidator.REST_PATH_UNKNOWN_VAR);
    }
  }

  @Check
  public void checkVariablesInEventMessage(final Event event) {
    String _message = event.getMessage();
    boolean _tripleNotEquals = (_message != null);
    if (_tripleNotEquals) {
      List<String> _asNames = CqrsAttributeExtensions.asNames(event.getAttributes());
      final List<String> vars = new ArrayList<String>(_asNames);
      AbstractMethod _origin = event.getOrigin();
      boolean _tripleNotEquals_1 = (_origin != null);
      if (_tripleNotEquals_1) {
        vars.addAll(CqrsParameterExtensions.asNames(event.getOrigin().getParameters()));
      }
      final String name = CqrsDslValidator.findUnknownVar(vars, event.getMessage());
      if ((name != null)) {
        this.error(
          (("A variable with the name \'" + name) + "\' is unknown"), event, 
          CqrsDslPackage.Literals.EVENT__MESSAGE, 
          CqrsDslValidator.EVENT_MSG_UNKNOWN_VAR);
      }
    }
  }

  /**
   * Checks that every variable in a command's message is one the command carries.
   * 
   * <p>Deliberately stricter than the event check above. An event's message is rendered by the JVM
   * alone, so anything Jakarta EL understands is fair game. A command's message is a confirmation
   * prompt shown <em>before</em> the command is sent, so the client renders it too - and a Dart
   * client has no EL engine. What a command may write is therefore the intersection: a plain
   * identifier or a dotted path, checked here so the two renderers cannot drift.
   */
  @Check
  public void checkVariablesInCommandMessage(final Command command) {
    String _message = command.getMessage();
    boolean _tripleNotEquals = (_message != null);
    if (_tripleNotEquals) {
      final List<String> vars = new ArrayList<String>();
      AbstractMethod _target = command.getTarget();
      boolean _tripleNotEquals_1 = (_target != null);
      if (_tripleNotEquals_1) {
        vars.addAll(CqrsParameterExtensions.asNames(command.getTarget().getParameters()));
      }
      vars.addAll(CqrsAttributeExtensions.asNames(command.getAttributes()));
      final Pair<String, String> problem = CqrsDslValidator.findUnusableCommandVar(vars, command.getMessage());
      if ((problem != null)) {
        this.error(
          problem.getValue(), command, 
          CqrsDslPackage.Literals.COMMAND__MESSAGE, 
          problem.getKey());
      }
    }
  }

  /**
   * Checks that a rule holds everything its refusal needs to name.
   * 
   * <p>An exception declares what it needs in order to say what it refused; a rule declares what it
   * decides from. The two overlap by name, which is why a rule commonly carries an attribute that
   * plays no part in its condition. Where they do not overlap the generated rule cannot construct its
   * own refusal - and without this that surfaces as a generator failure at the far end of a release
   * chain, or as generated Java missing an argument.
   * 
   * <p>Only where a condition is declared, because that is what decides whether a class is generated
   * at all. A rule without one is written by hand and constructs its refusal however it likes; a rule
   * that has not yet been given its inputs is not yet wrong, it is not yet finished.
   */
  @Check
  public void checkRuleSuppliesItsException(final BusinessRule rule) {
    if (((rule.getException() == null) || (rule.getRequires() == null))) {
      return;
    }
    final List<String> declared = CqrsAttributeExtensions.asNames(rule.getAttributes());
    EList<Attribute> _attributes = rule.getException().getAttributes();
    for (final Attribute attribute : _attributes) {
      boolean _contains = declared.contains(attribute.getName());
      boolean _not = (!_contains);
      if (_not) {
        String _name = rule.getException().getName();
        String _plus = (_name + " needs \'");
        String _name_1 = attribute.getName();
        String _plus_1 = (_plus + _name_1);
        String _plus_2 = (_plus_1 + "\' to say what it refused, and ");
        String _name_2 = rule.getName();
        String _plus_3 = (_plus_2 + _name_2);
        String _plus_4 = (_plus_3 + " does not declare it");
        this.error(_plus_4, rule, 
          CqrsDslPackage.Literals.BUSINESS_RULE__EXCEPTION, 
          CqrsDslValidator.RULE_EXCEPTION_NOT_SUPPLIED);
        return;
      }
    }
  }

  /**
   * Two attributes compared against each other must be of the same type.
   * 
   * <p>Nothing else catches this. The scope lets any of the rule's own attributes stand on the right,
   * '==' generates 'Objects.equals', and Java is happy to compare two unrelated types - so a condition
   * over a 'ReceiptType' and a 'CategoryType' links, compiles, runs, and is always false. A rule that
   * always refuses is the worst of the failures this generator exists to prevent, because everything
   * about it looks like it works.
   */
  @Check
  public void checkComparisonOperandTypes(final RuleComparison comparison) {
    final RuleAttrRef left = comparison.getLeft();
    final RuleOperand right = comparison.getRight();
    if (((!(left instanceof RuleAttrRef)) || (!(right instanceof RuleRefOperand)))) {
      return;
    }
    final Attribute leftAttribute = ((RuleAttrRef) left).getAttribute();
    Type _type = null;
    if (leftAttribute!=null) {
      _type=leftAttribute.getType();
    }
    final Type leftType = _type;
    final EObject target = ((RuleRefOperand) right).getTarget();
    if (((leftType == null) || (!(target instanceof Attribute)))) {
      return;
    }
    final Attribute rightAttribute = ((Attribute) target);
    final Type rightType = rightAttribute.getType();
    if (((rightType != null) && (leftType != rightType))) {
      String _name = leftAttribute.getName();
      String _plus = ("\'" + _name);
      String _plus_1 = (_plus + "\' is a ");
      String _name_1 = leftType.getName();
      String _plus_2 = (_plus_1 + _name_1);
      String _plus_3 = (_plus_2 + " and \'");
      String _name_2 = rightAttribute.getName();
      String _plus_4 = (_plus_3 + _name_2);
      String _plus_5 = (_plus_4 + "\' is a ");
      String _name_3 = rightType.getName();
      String _plus_6 = (_plus_5 + _name_3);
      String _plus_7 = (_plus_6 + "; comparing them is always false");
      this.error(_plus_7, comparison, 
        CqrsDslPackage.Literals.RULE_COMPARISON__RIGHT, 
        CqrsDslValidator.RULE_COMPARISON_TYPE_MISMATCH);
    }
  }

  /**
   * Checks that a rule usage hands over as many values as the rule declares.
   * 
   * <p>The actuals bind positionally, so one too few or one too many silently shifts every value
   * after it - and because everything here is a reference rather than a literal, the result usually
   * still type-checks.
   */
  @Check
  public void checkRuleActuals(final BusinessRuleInstance instance) {
    final BusinessRule rule = instance.getBusinessRule();
    if (((rule == null) || rule.eIsProxy())) {
      return;
    }
    final int expected = CqrsCollectionExtensions.<Attribute>nullSafe(rule.getAttributes()).size();
    final int actual = CqrsCollectionExtensions.<RuleArgument>nullSafe(instance.getParams()).size();
    if ((expected != actual)) {
      String _name = rule.getName();
      String _plus = (_name + " decides from ");
      String _plus_1 = (_plus + Integer.valueOf(expected));
      String _plus_2 = (_plus_1 + " value(s), but ");
      String _plus_3 = (_plus_2 + Integer.valueOf(actual));
      String _plus_4 = (_plus_3 + " were given");
      this.error(_plus_4, instance, 
        CqrsDslPackage.Literals.BUSINESS_RULE_INSTANCE__BUSINESS_RULE, 
        CqrsDslValidator.RULE_ACTUALS_MISMATCH);
    }
  }

  @Check
  public void checkOwnIdOutsideConstructor(final IdentityArgument argument) {
    final Constructor constructor = EcoreUtil2.<Constructor>getContainerOfType(argument, Constructor.class);
    if ((constructor != null)) {
      this.error(
        "\'own-id\' has nothing to read in a constructor, which is what creates the identity", argument, 
        null, 
        CqrsDslValidator.RULE_OWN_ID_IN_CONSTRUCTOR);
    }
  }

  /**
   * A constructor has no prior state either. 'own' names what the carrier holds now, as against what
   * the operation would give it, and before the carrier exists there is no "now" to read.
   */
  @Check
  public void checkOwnAttributeOutsideConstructor(final CarrierAttributeArgument argument) {
    final Constructor constructor = EcoreUtil2.<Constructor>getContainerOfType(argument, Constructor.class);
    if ((constructor != null)) {
      Attribute _attribute = argument.getAttribute();
      String _name = null;
      if (_attribute!=null) {
        _name=_attribute.getName();
      }
      String _plus = ("\'own " + _name);
      String _plus_1 = (_plus + "\' has nothing to read in a constructor, which is what creates the state");
      this.error(_plus_1, argument, 
        null, 
        CqrsDslValidator.RULE_OWN_ATTRIBUTE_IN_CONSTRUCTOR);
    }
  }

  @Check
  public void checkViewCronSchedule(final View view) {
    if (((view.getCron() != null) && (!SpringCronExpression.isValid(view.getCron())))) {
      String _cron = view.getCron();
      String _plus = ("Invalid Spring cron expression: \'" + _cron);
      String _plus_1 = (_plus + "\'");
      this.error(_plus_1, view, 
        CqrsDslPackage.Literals.VIEW__CRON, 
        CqrsDslValidator.INVALID_CRON_EXPRESSION);
    }
  }

  @Check
  public void checkProcessManagerCronSchedule(final ProcessManager pm) {
    if (((pm.getCron() != null) && (!SpringCronExpression.isValid(pm.getCron())))) {
      String _cron = pm.getCron();
      String _plus = ("Invalid Spring cron expression: \'" + _cron);
      String _plus_1 = (_plus + "\'");
      this.error(_plus_1, pm, 
        CqrsDslPackage.Literals.PROCESS_MANAGER__CRON, 
        CqrsDslValidator.INVALID_CRON_EXPRESSION);
    }
  }

  @Check
  public void checkHintJsonSchema(final Hint hint) {
    final String schema = CqrsHintJson.schemaForHintName(hint.getName());
    if (((schema != null) && (hint.getJson() != null))) {
      List<String> _validate = CqrsHintJson.validate(hint.getJson(), schema);
      for (final String msg : _validate) {
        this.error(msg, hint, CqrsDslPackage.Literals.HINT__JSON, CqrsDslValidator.HINT_JSON_SCHEMA_VIOLATION);
      }
    }
    if ((Objects.equals("JpaHint", this.simpleHintName(hint.getName())) && (!(hint.eContainer() instanceof View)))) {
      this.warning(
        "JpaHint only generates code inside a view", hint, 
        CqrsDslPackage.Literals.HINT__NAME, 
        CqrsDslValidator.JPA_HINT_OUTSIDE_VIEW);
    }
  }

  private String simpleHintName(final String name) {
    String _xblockexpression = null;
    {
      if ((name == null)) {
        return null;
      }
      final int p = name.lastIndexOf(".");
      String _xifexpression = null;
      if ((p < 0)) {
        _xifexpression = name;
      } else {
        _xifexpression = name.substring((p + 1));
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }

  @Check
  public void checkUniqueProcessStateNames(final ProcessManager pm) {
    final Set<String> seen = new HashSet<String>();
    EList<ProcessState> _states = pm.getStates();
    for (final ProcessState state : _states) {
      boolean _add = seen.add(state.getName());
      boolean _not = (!_add);
      if (_not) {
        String _name = state.getName();
        String _plus = ("Duplicate process state \'" + _name);
        String _plus_1 = (_plus + "\'");
        this.error(_plus_1, state, 
          CqrsDslPackage.Literals.PROCESS_STATE__NAME, 
          CqrsDslValidator.PROCESS_STATE_DUPLICATE);
      }
    }
  }

  @Check
  public void checkCorrelateByAttribute(final ProcessReaction reaction) {
    final String key = reaction.getCorrelationKey();
    final Event event = reaction.getEvent();
    if ((((key != null) && (event != null)) && (!event.eIsProxy()))) {
      List<String> _asNames = CqrsAttributeExtensions.asNames(event.getAttributes());
      final List<String> vars = new ArrayList<String>(_asNames);
      AbstractMethod _origin = event.getOrigin();
      boolean _tripleNotEquals = (_origin != null);
      if (_tripleNotEquals) {
        vars.addAll(CqrsParameterExtensions.asNames(event.getOrigin().getParameters()));
      }
      boolean _contains = vars.contains(key);
      boolean _not = (!_contains);
      if (_not) {
        String _name = event.getName();
        String _plus = ((("The correlation key \'" + key) + "\' is not an attribute of event \'") + _name);
        String _plus_1 = (_plus + "\'");
        this.error(_plus_1, reaction, 
          CqrsDslPackage.Literals.PROCESS_REACTION__CORRELATION_KEY, 
          CqrsDslValidator.PROCESS_CORRELATION_KEY_UNKNOWN);
      }
    }
  }

  @Check
  public void checkUniqueExceptionUID(final org.fuin.dsl.cqrs.cqrsDsl.Exception ex) {
    String name = null;
    int max = 0;
    final Iterator<org.fuin.dsl.cqrs.cqrsDsl.Exception> allExceptions = this.getAllExceptions(ex).iterator();
    while (allExceptions.hasNext()) {
      {
        final org.fuin.dsl.cqrs.cqrsDsl.Exception other = allExceptions.next();
        if (((other.getCid() > max) && CqrsEObjectExtensions.getContext(ex).getName().equals(CqrsEObjectExtensions.getContext(other).getName()))) {
          max = other.getCid();
        }
        if ((((((name == null) && (!Objects.equals(ex, other))) && (ex.getCid() > 0)) && (ex.getCid() == other.getCid())) && 
          CqrsEObjectExtensions.getContext(ex).getName().equals(CqrsEObjectExtensions.getContext(other).getName()))) {
          name = other.getName();
        }
      }
    }
    if ((name != null)) {
      final String nextId = ("" + Integer.valueOf((max + 1)));
      this.error(
        (("The CID is already used by exception \'" + name) + "\'"), ex, 
        CqrsDslPackage.Literals.EXCEPTION__CID, 
        CqrsDslValidator.EXCEPTION_DUPLICATE_CID, nextId);
    }
  }

  @Check
  public void checkAttributeInvariantsTargetType(final Attribute attribute) {
    if (((attribute.getInvariants() != null) && (attribute.getInvariants().getConstraintInstances() != null))) {
      EList<ConstraintInstance> _constraintInstances = attribute.getInvariants().getConstraintInstances();
      for (final ConstraintInstance constraintInstance : _constraintInstances) {
        if ((((constraintInstance.getConstraint().getInput() != null) && (((Object[])Conversions.unwrapArray(constraintInstance.getConstraint().getInput(), Object.class)).length > 0)) && (!constraintInstance.getConstraint().getInput().contains(attribute.getType())))) {
          String _typeNames = CqrsDslValidator.typeNames(constraintInstance.getConstraint().getInput());
          String _plus = ("The allowed input types of the constraint (" + _typeNames);
          String _plus_1 = (_plus + 
            ") do not match the attribute type");
          this.error(_plus_1, constraintInstance, 
            CqrsDslPackage.Literals.CONSTRAINT_INSTANCE__CONSTRAINT, 
            CqrsDslValidator.ATTRIBUTE_INVARIANT_WRONG_TARGET_TYPE);
        }
      }
    }
  }

  @Check
  public void checkParameterConstraintsTargetType(final Parameter parameter) {
    if (((parameter.getPreconditions() != null) && (parameter.getPreconditions().getConstraintInstances() != null))) {
      EList<ConstraintInstance> _constraintInstances = parameter.getPreconditions().getConstraintInstances();
      for (final ConstraintInstance constraintInstance : _constraintInstances) {
        boolean _contains = constraintInstance.getConstraint().getInput().contains(parameter.getType());
        boolean _not = (!_contains);
        if (_not) {
          String _typeNames = CqrsDslValidator.typeNames(constraintInstance.getConstraint().getInput());
          String _plus = ("The input type of the constraint (" + _typeNames);
          String _plus_1 = (_plus + 
            ") does not match the parameter type");
          this.error(_plus_1, constraintInstance, 
            CqrsDslPackage.Literals.CONSTRAINT_INSTANCE__CONSTRAINT, 
            CqrsDslValidator.PARAMETER_CONSTRAINT_WRONG_TARGET_TYPE);
        }
      }
    }
  }

  @Check
  public void checkInternalTypeInvariantsTargetType(final InternalType internalType) {
    if (((internalType.getInvariants() != null) && (internalType.getInvariants().getConstraintInstances() != null))) {
      EList<ConstraintInstance> _constraintInstances = internalType.getInvariants().getConstraintInstances();
      for (final ConstraintInstance constraintInstance : _constraintInstances) {
        boolean _contains = constraintInstance.getConstraint().getInput().contains(internalType);
        boolean _not = (!_contains);
        if (_not) {
          String _typeNames = CqrsDslValidator.typeNames(constraintInstance.getConstraint().getInput());
          String _plus = ("The input type of the constraint (" + _typeNames);
          String _plus_1 = (_plus + 
            ") does not match this type");
          this.error(_plus_1, constraintInstance, 
            CqrsDslPackage.Literals.CONSTRAINT_INSTANCE__CONSTRAINT, 
            CqrsDslValidator.INTERNAL_TYPE_INVARIANT_WRONG_TARGET_TYPE);
        }
      }
    }
  }

  @Check
  public void checkWeakConsistency(final Consistency consistency) {
    if ((Objects.equals(consistency.getLevel(), ConsistencyLevel.WEAK) && (consistency.getWeakConsistency() == null))) {
      this.error(
        "You must define the details for weak consistency", consistency, 
        CqrsDslPackage.Literals.CONSISTENCY__WEAK_CONSISTENCY, 
        CqrsDslValidator.WEAK_CONSISTENCY_REQUIRES_DETAILS);
    }
    if ((Objects.equals(consistency.getLevel(), ConsistencyLevel.STRONG) && (consistency.getWeakConsistency() != null))) {
      this.error(
        "No details required for strong consistency", consistency, 
        CqrsDslPackage.Literals.CONSISTENCY__WEAK_CONSISTENCY, 
        CqrsDslValidator.STRONG_CONSISTENCY_DOES_NOT_ALLOW_DETAILS);
    }
  }

  @Check
  public void checkAggregateIdIdentifies(final AggregateId aggregateId) {
    EObject _eContainer = aggregateId.eContainer();
    if ((_eContainer instanceof Aggregate)) {
      if (((aggregateId.getAggregate() != null) && (!Objects.equals(aggregateId.getAggregate(), aggregateId.eContainer())))) {
        this.error(
          "An ID defined in an aggregate can only identify the parent aggregate", aggregateId, 
          CqrsDslPackage.Literals.AGGREGATE_ID__AGGREGATE, 
          CqrsDslValidator.WRONG_IDENTIFIES_AGGREGATE);
      }
    } else {
      Aggregate _aggregate = aggregateId.getAggregate();
      boolean _tripleEquals = (_aggregate == null);
      if (_tripleEquals) {
        this.error(
          "An ID defined outside an aggregate must use the \'identifies\' expression", aggregateId, 
          CqrsDslPackage.Literals.AGGREGATE_ID__AGGREGATE, 
          CqrsDslValidator.IDENTIFIES_AGGREGATE_NULL);
      }
    }
  }

  @Check
  public void checkEntityIdIdentifies(final EntityId entityId) {
    EObject _eContainer = entityId.eContainer();
    if ((_eContainer instanceof Entity)) {
      if (((entityId.getEntity() != null) && (!Objects.equals(entityId.getEntity(), entityId.eContainer())))) {
        this.error(
          "An ID defined in an entity can only identify the parent entity", entityId, 
          CqrsDslPackage.Literals.ENTITY_ID__ENTITY, 
          CqrsDslValidator.WRONG_IDENTIFIES_ENTITY);
      }
    } else {
      Entity _entity = entityId.getEntity();
      boolean _tripleEquals = (_entity == null);
      if (_tripleEquals) {
        this.error(
          "An ID defined outside an entity must use the \'identifies\' expression", entityId, 
          CqrsDslPackage.Literals.ENTITY_ID__ENTITY, 
          CqrsDslValidator.IDENTIFIES_ENTITY_NULL);
      }
    }
  }

  @Check
  public void checkEntityRoot(final Entity entity) {
    EObject _eContainer = entity.eContainer();
    if ((_eContainer instanceof Aggregate)) {
      if (((entity.getRoot() != null) && (!Objects.equals(entity.getRoot(), entity.eContainer())))) {
        this.error(
          "An entity defined in an aggregate can only reference the parent aggregate", entity, 
          CqrsDslPackage.Literals.ENTITY__ROOT, 
          CqrsDslValidator.WRONG_ROOT_AGGREGATE);
      }
    } else {
      Aggregate _root = entity.getRoot();
      boolean _tripleEquals = (_root == null);
      if (_tripleEquals) {
        this.error(
          "An entity defined outside an aggregate must use the \'root\' expression", entity, 
          CqrsDslPackage.Literals.ENTITY__ROOT, 
          CqrsDslValidator.ROOT_NULL);
      }
    }
  }

  @Check
  public void checkEntityHasId(final Entity entity) {
    EntityId _idType = entity.getIdType();
    boolean _tripleEquals = (_idType == null);
    if (_tripleEquals) {
      EntityId _entityId = CqrsEntityExtensions.getEntityId(entity);
      boolean _tripleEquals_1 = (_entityId == null);
      if (_tripleEquals_1) {
        this.error(
          "Entity does not define an ID", entity, 
          CqrsDslPackage.Literals.ENTITY__ID_TYPE, 
          CqrsDslValidator.ENTITY_WITHOUT_ID);
      }
    } else {
      EntityId _entityId_1 = CqrsEntityExtensions.getEntityId(entity);
      boolean _tripleNotEquals = (_entityId_1 != null);
      if (_tripleNotEquals) {
        this.error(
          "Entity cannot not reference an ID using \'identifier\' and define another inside the aggregate", entity, 
          CqrsDslPackage.Literals.ENTITY__ID_TYPE, 
          CqrsDslValidator.ENTITY_WITH_DUPLICATE_ID);
      }
    }
  }

  @Check
  public void checkAggregateHasId(final Aggregate aggregate) {
    AggregateId _idType = aggregate.getIdType();
    boolean _tripleEquals = (_idType == null);
    if (_tripleEquals) {
      AggregateId _aggregateId = CqrsAggregateExtensions.getAggregateId(aggregate);
      boolean _tripleEquals_1 = (_aggregateId == null);
      if (_tripleEquals_1) {
        this.error(
          "Aggregate does not define an ID", aggregate, 
          CqrsDslPackage.Literals.AGGREGATE__ID_TYPE, 
          CqrsDslValidator.AGGREGATE_WITHOUT_ID);
      }
    } else {
      AggregateId _aggregateId_1 = CqrsAggregateExtensions.getAggregateId(aggregate);
      boolean _tripleNotEquals = (_aggregateId_1 != null);
      if (_tripleNotEquals) {
        this.error(
          "Aggregate cannot not reference an ID using \'identifier\' and define another inside the aggregate", aggregate, 
          CqrsDslPackage.Literals.AGGREGATE__ID_TYPE, 
          CqrsDslValidator.AGGREGATE_WITH_DUPLICATE_ID);
      }
    }
  }

  @Check
  public void checkOnlyOneAggregateId(final Aggregate aggregate) {
    int _size = IterableExtensions.size(Iterables.<AggregateId>filter(CqrsCollectionExtensions.<AbstractElement>nullSafe(aggregate.getElements()), AggregateId.class));
    boolean _greaterThan = (_size > 1);
    if (_greaterThan) {
      this.error(
        "Only one \'aggregate-id\' can be defined inside an aggregate", aggregate, 
        CqrsDslPackage.Literals.ABSTRACT_ENTITY__ELEMENTS, 
        CqrsDslValidator.MULTIPLE_AGGREGATE_ID_ELEMENTS);
    }
  }

  /**
   * Restricts what an aggregate may hold as a nested element. Only the 'elements' list is meant: an
   * aggregate's own 'business-rule' is an AbstractElement too - so that a shared rule can be a module
   * element - but it lives in 'businessRules' and is not one of the nested elements this rule is about.
   */
  @Check
  public void checkAllowedAggregateElements(final AbstractElement el) {
    if ((((el.eContainer() instanceof Aggregate) && (el.eContainingFeature() == CqrsDslPackage.Literals.ABSTRACT_ENTITY__ELEMENTS)) && 
      (!(((((el instanceof AggregateId) || (el instanceof Entity)) || (el instanceof Event)) || (el instanceof Command)) || (el instanceof ValueObject))))) {
      this.error(
        "Allowed elements in an aggregate are: \'aggregate-id\', \'entity\', \'event\', \'command\' and \'value-object\'", el, 
        CqrsDslPackage.Literals.ABSTRACT_ELEMENT__NAME, 
        CqrsDslValidator.ILLEGAL_AGGREGATE_ELEMENT);
    }
  }

  @Check
  public void checkOnlyOneEntityId(final Entity entity) {
    int _size = IterableExtensions.size(Iterables.<EntityId>filter(CqrsCollectionExtensions.<AbstractElement>nullSafe(entity.getElements()), EntityId.class));
    boolean _greaterThan = (_size > 1);
    if (_greaterThan) {
      this.error(
        "Only one \'entity-id\' can be defined inside an entity", entity, 
        CqrsDslPackage.Literals.ABSTRACT_ENTITY__ELEMENTS, 
        CqrsDslValidator.MULTIPLE_ENTITY_ID_ELEMENTS);
    }
  }

  /**
   * The same for an entity: its own 'business-rule' is not one of its nested elements.
   */
  @Check
  public void checkAllowedEntityElements(final AbstractElement el) {
    if ((((el.eContainer() instanceof Entity) && (el.eContainingFeature() == CqrsDslPackage.Literals.ABSTRACT_ENTITY__ELEMENTS)) && 
      (!(((el instanceof EntityId) || (el instanceof Event)) || (el instanceof ValueObject))))) {
      this.error(
        "Allowed elements in an entity are: \'entity-id\', \'event\' and \'value-object\'", el, 
        CqrsDslPackage.Literals.ABSTRACT_ELEMENT__NAME, 
        CqrsDslValidator.ILLEGAL_ENTITY_ELEMENT);
    }
  }

  @Check
  public void checkGenericArgs(final Variable v) {
    Type _type = v.getType();
    if ((_type instanceof ExternalType)) {
      Type _type_1 = v.getType();
      final ExternalType type = ((ExternalType) _type_1);
      GenericArgs _generics = v.getGenerics();
      boolean _tripleEquals = (_generics == null);
      if (_tripleEquals) {
        int _generics_1 = type.getGenerics();
        boolean _greaterThan = (_generics_1 > 0);
        if (_greaterThan) {
          int _generics_2 = type.getGenerics();
          String _plus = ("The number of arguments does not match the number required by the type: " + Integer.valueOf(_generics_2));
          this.error(_plus, v, 
            CqrsDslPackage.Literals.VARIABLE__GENERICS, 
            CqrsDslValidator.VAR_GENERICS_COUNT_MISMATCH);
        }
      } else {
        int _size = CqrsCollectionExtensions.<Type>nullSafe(v.getGenerics().getArgs()).size();
        int _generics_3 = type.getGenerics();
        boolean _notEquals = (_size != _generics_3);
        if (_notEquals) {
          int _generics_4 = type.getGenerics();
          String _plus_1 = ("The number of arguments does not match the number required by the type: " + Integer.valueOf(_generics_4));
          this.error(_plus_1, v, 
            CqrsDslPackage.Literals.VARIABLE__GENERICS, 
            CqrsDslValidator.VAR_GENERICS_COUNT_MISMATCH);
        }
      }
    }
  }

  @Check
  public void checkReturnTypeGenericArgs(final ReturnType rt) {
    Type _type = rt.getType();
    if ((_type instanceof ExternalType)) {
      Type _type_1 = rt.getType();
      final ExternalType type = ((ExternalType) _type_1);
      GenericArgs _generics = rt.getGenerics();
      boolean _tripleEquals = (_generics == null);
      if (_tripleEquals) {
        int _generics_1 = type.getGenerics();
        boolean _greaterThan = (_generics_1 > 0);
        if (_greaterThan) {
          int _generics_2 = type.getGenerics();
          String _plus = ("The number of arguments does not match the number required by the type: " + Integer.valueOf(_generics_2));
          this.error(_plus, rt, 
            CqrsDslPackage.Literals.RETURN_TYPE__GENERICS, 
            CqrsDslValidator.RETURN_TYPE_GENERICS_COUNT_MISMATCH);
        }
      } else {
        int _size = CqrsCollectionExtensions.<Type>nullSafe(rt.getGenerics().getArgs()).size();
        int _generics_3 = type.getGenerics();
        boolean _notEquals = (_size != _generics_3);
        if (_notEquals) {
          int _generics_4 = type.getGenerics();
          String _plus_1 = ("The number of arguments does not match the number required by the type: " + Integer.valueOf(_generics_4));
          this.error(_plus_1, rt, 
            CqrsDslPackage.Literals.RETURN_TYPE__GENERICS, 
            CqrsDslValidator.RETURN_TYPE_GENERICS_COUNT_MISMATCH);
        }
      }
    }
  }

  @Check
  public void checkAnnotationInstanceArgs(final AnnotationInstance ai) {
    int _size = CqrsCollectionExtensions.<Attribute>nullSafe(ai.getAnnotation().getAttributes()).size();
    int _size_1 = CqrsCollectionExtensions.<Literal>nullSafe(ai.getParams()).size();
    boolean _tripleNotEquals = (_size != _size_1);
    if (_tripleNotEquals) {
      String _name = ai.getAnnotation().getName();
      String _plus = ("The number of arguments does not match the number required by the type: " + _name);
      this.error(_plus, ai, 
        CqrsDslPackage.Literals.ANNOTATION_INSTANCE__PARAMS, 
        CqrsDslValidator.ANNOTATION_PARAM_COUNT_MISMATCH);
    }
  }

  @Check
  public void checkValueObjectBaseHasNoConstructorsOrMethods(final ValueObject vo) {
    ExternalType _base = vo.getBase();
    boolean _tripleNotEquals = (_base != null);
    if (_tripleNotEquals) {
      boolean _isEmpty = CqrsCollectionExtensions.<Constructor>nullSafe(vo.getConstructors()).isEmpty();
      boolean _not = (!_isEmpty);
      if (_not) {
        this.error(
          "A value object with a \'base\' is not allowed to have constructors", vo, 
          CqrsDslPackage.Literals.ABSTRACT_VO__CONSTRUCTORS, 
          CqrsDslValidator.VALUE_OBJECT_BASE_NO_CONSTRUCTORS_OR_METHODS);
      }
      boolean _isEmpty_1 = CqrsCollectionExtensions.<Method>nullSafe(vo.getMethods()).isEmpty();
      boolean _not_1 = (!_isEmpty_1);
      if (_not_1) {
        this.error(
          "A value object with a \'base\' is not allowed to have methods", vo, 
          CqrsDslPackage.Literals.ABSTRACT_VO__METHODS, 
          CqrsDslValidator.VALUE_OBJECT_BASE_NO_CONSTRUCTORS_OR_METHODS);
      }
    }
  }

  private Set<org.fuin.dsl.cqrs.cqrsDsl.Exception> getAllExceptions(final EObject obj) {
    final Set<org.fuin.dsl.cqrs.cqrsDsl.Exception> list = new HashSet<org.fuin.dsl.cqrs.cqrsDsl.Exception>();
    final Resource resource = obj.eResource();
    final IResourceDescriptions resourceDescriptions = this.resourceDescriptionsProvider.getResourceDescriptions(resource);
    final IResourceDescription resourceDescription = resourceDescriptions.getResourceDescription(resource.getURI());
    final List<IContainer> containers = this.containerManager.getVisibleContainers(resourceDescription, resourceDescriptions);
    for (final IContainer container : containers) {
      Iterable<IEObjectDescription> _exportedObjects = container.getExportedObjects();
      for (final IEObjectDescription descr : _exportedObjects) {
        {
          final EObject eObjectOrProxy = descr.getEObjectOrProxy();
          if ((eObjectOrProxy instanceof org.fuin.dsl.cqrs.cqrsDsl.Exception)) {
            EObject _resolve = EcoreUtil.resolve(eObjectOrProxy, obj);
            final org.fuin.dsl.cqrs.cqrsDsl.Exception ex = ((org.fuin.dsl.cqrs.cqrsDsl.Exception) _resolve);
            list.add(ex);
          }
        }
      }
    }
    return list;
  }

  private static String findUnknownVar(final List<String> vars, final String msg) {
    int end = (-1);
    int from = 0;
    int start = (-1);
    while (((start = msg.indexOf("${", from)) > (-1))) {
      {
        end = msg.indexOf("}", (start + 1));
        if ((end == (-1))) {
          from = msg.length();
        } else {
          String name = msg.substring((start + 2), end);
          if (((CqrsDslValidator.isSimpleVariableName(name) && (!vars.contains(name))) && (!name.equals("entityIdPath")))) {
            return name;
          }
          from = (end + 1);
        }
      }
    }
    return null;
  }

  /**
   * Returns the first "{name}" placeholder of a REST path that is not backed by one of the given
   * parameter names, or NULL if all of them are known. Unlike a message variable a path variable
   * has no "$" prefix and is always a plain identifier.
   */
  private static String findUnknownPathVar(final List<String> vars, final String path) {
    int end = (-1);
    int from = 0;
    int start = (-1);
    while (((start = path.indexOf("{", from)) > (-1))) {
      {
        end = path.indexOf("}", (start + 1));
        if ((end == (-1))) {
          from = path.length();
        } else {
          String name = path.substring((start + 1), end);
          if ((CqrsDslValidator.isSimpleVariableName(name) && (!vars.contains(name)))) {
            return name;
          }
          from = (end + 1);
        }
      }
    }
    return null;
  }

  private static boolean isSimpleVariableName(final String name) {
    return name.matches("[A-Za-z_$][A-Za-z0-9_$]*");
  }

  /**
   * Returns the first "${...}" of a command message that will not render, as an issue code paired
   * with what to tell the author, or NULL if every one of them is usable. Three different defects,
   * so three codes: nothing closes it, no renderer understands it, or nothing supplies it.
   */
  private static Pair<String, String> findUnusableCommandVar(final List<String> vars, final String msg) {
    int from = 0;
    int start = (-1);
    while (((start = msg.indexOf("${", from)) > (-1))) {
      {
        final int end = msg.indexOf("}", (start + 1));
        if ((end == (-1))) {
          String _substring = msg.substring((start + 2));
          String _plus = ("The variable \'" + _substring);
          String _plus_1 = (_plus + "\' is not closed with \'}\'");
          return Pair.<String, String>of(CqrsDslValidator.COMMAND_MSG_UNCLOSED_VAR, _plus_1);
        }
        final String expr = msg.substring((start + 2), end);
        boolean _isVariablePath = CqrsDslValidator.isVariablePath(expr);
        boolean _not = (!_isVariablePath);
        if (_not) {
          return Pair.<String, String>of(CqrsDslValidator.COMMAND_MSG_NOT_A_PATH, (((("\'" + expr) + "\' is not a plain variable or a dotted ") + "path. A command\'s message is rendered by the client as well, which has no ") + "expression language"));
        }
        if (((!vars.contains(CqrsDslValidator.rootOf(expr))) && (!Objects.equals(CqrsDslValidator.rootOf(expr), "entityIdPath")))) {
          String _rootOf = CqrsDslValidator.rootOf(expr);
          String _plus_2 = ("A variable with the name \'" + _rootOf);
          String _plus_3 = (_plus_2 + "\' is unknown");
          return Pair.<String, String>of(CqrsDslValidator.COMMAND_MSG_UNKNOWN_VAR, _plus_3);
        }
        from = (end + 1);
      }
    }
    return null;
  }

  /**
   * Whether the expression is a plain identifier or identifiers joined by dots, and nothing else.
   */
  private static boolean isVariablePath(final String expr) {
    return expr.matches("[A-Za-z_$][A-Za-z0-9_$]*(\\.[A-Za-z_$][A-Za-z0-9_$]*)*");
  }

  /**
   * The variable a path starts at - "provider" in "provider.id" - which is what has to exist.
   */
  private static String rootOf(final String expr) {
    final int dot = expr.indexOf(".");
    String _xifexpression = null;
    if ((dot == (-1))) {
      _xifexpression = expr;
    } else {
      _xifexpression = expr.substring(0, dot);
    }
    return _xifexpression;
  }

  private static String typeNames(final List<Type> types) {
    if ((types == null)) {
      return "";
    }
    final StringBuilder sb = new StringBuilder();
    for (final Type type : types) {
      {
        int _length = sb.length();
        boolean _greaterThan = (_length > 0);
        if (_greaterThan) {
          sb.append(", ");
        }
        sb.append(type.getName());
      }
    }
    return sb.toString();
  }

  private static List<Type> types(final EList<Attribute> attributes) {
    if ((attributes == null)) {
      return Collections.<Type>emptyList();
    }
    final ArrayList<Type> list = new ArrayList<Type>();
    for (final Attribute attribute : attributes) {
      list.add(attribute.getType());
    }
    return list;
  }

  /**
   * Warns when a view row offers a command whose client-answerable gates it cannot answer.
   * 
   * <p>A menu is drawn on a row, and a command gated by a rule over the aggregate's own state can be
   * left out of that menu rather than offered and refused. The client decides that from what the row
   * publishes, so a row that offers the command and omits what the gate reads makes the gate work on
   * one screen and quietly do nothing on another. The silence is the problem: an unanswerable gate is
   * indistinguishable from a gate nobody wrote.
   * 
   * <p><b>A warning rather than an error, deliberately.</b> Whether a row publishes what a rule reads
   * is a modelling decision with real costs on the other side - a count is what a person wants to read
   * where a collection is what the rule asks, and an identity provider's own id has no business on a
   * row merely so a menu can be shorter. So this states the gap and leaves the choice; what it removes
   * is the silence, not the omission.
   * 
   * <p>It is also conservative in one direction and blind in another. Conservative, because it asks for
   * every value the rule is handed rather than only those its condition reads - which is what the
   * client actually needs to construct the rule at all. Blind, because a fact no view projects matches
   * no row and is never reported: a row missing one attribute is caught, an aggregate with no row is
   * not.
   * 
   * <p><b>The build is the enforcement point.</b> SrcGen4J parses the whole model into one resource
   * set, so a build sees every command and every row. An editor validates one resource and reaches the
   * rest through the index, so a gate declared in a file that is not open may go unreported - the same
   * trade the module cycle check makes.
   */
  @Check
  public void checkRowAnswersTheGatesItOffers(final ValueObject row) {
    Resource _eResource = row.eResource();
    URI _uRI = null;
    if (_eResource!=null) {
      _uRI=_eResource.getURI();
    }
    boolean _isArchived = CqrsModelArchives.isArchived(_uRI);
    if (_isArchived) {
      return;
    }
    final Attribute identity = CqrsAbstractVOExtensions.rowIdentity(row);
    if (((identity == null) || (identity.getType() == null))) {
      return;
    }
    boolean _returnedByAView = this.returnedByAView(row);
    boolean _not = (!_returnedByAView);
    if (_not) {
      return;
    }
    final HashSet<String> published = new HashSet<String>();
    List<Attribute> _nullSafe = CqrsCollectionExtensions.<Attribute>nullSafe(row.getAttributes());
    for (final Attribute attribute : _nullSafe) {
      published.add(attribute.getName());
    }
    List<Command> _commandsAddressing = this.commandsAddressing(identity.getType(), row);
    for (final Command command : _commandsAddressing) {
      {
        final AbstractMethod operation = command.getTarget();
        if (((operation == null) || (operation instanceof Constructor))) {
        } else {
          List<BusinessRuleInstance> _nullSafe_1 = CqrsBusinessRulesExtensions.nullSafe(operation.getBusinessRules());
          for (final BusinessRuleInstance instance : _nullSafe_1) {
            this.reportUnanswerable(row, command, instance, published);
          }
        }
      }
    }
  }

  /**
   * One warning per rule the row offers and cannot answer, naming what it would have to publish.
   */
  private void reportUnanswerable(final ValueObject row, final Command command, final BusinessRuleInstance instance, final Set<String> published) {
    boolean _clientAnswerable = CqrsBusinessRulesExtensions.clientAnswerable(instance);
    boolean _not = (!_clientAnswerable);
    if (_not) {
      return;
    }
    final ArrayList<String> missing = new ArrayList<String>();
    List<String> _carrierAttributesRead = CqrsBusinessRulesExtensions.carrierAttributesRead(instance);
    for (final String name : _carrierAttributesRead) {
      boolean _contains = published.contains(name);
      boolean _not_1 = (!_contains);
      if (_not_1) {
        missing.add(name);
      }
    }
    boolean _isEmpty = missing.isEmpty();
    if (_isEmpty) {
      return;
    }
    String _name = row.getName();
    String _plus = ("\'" + _name);
    String _plus_1 = (_plus + "\' offers \'");
    String _name_1 = command.getName();
    String _plus_2 = (_plus_1 + _name_1);
    String _plus_3 = (_plus_2 + "\', which is gated by \'");
    String _name_2 = instance.getBusinessRule().getName();
    String _plus_4 = (_plus_3 + _name_2);
    String _plus_5 = (_plus_4 + "\', but does not publish ");
    String _quoted = CqrsDslValidator.quoted(missing);
    String _plus_6 = (_plus_5 + _quoted);
    String _plus_7 = (_plus_6 + " - so a client cannot tell whether to offer the action and always will");
    this.warning(_plus_7, row, CqrsDslPackage.Literals.ABSTRACT_ELEMENT__NAME, CqrsDslValidator.ROW_CANNOT_ANSWER_GATE);
  }

  /**
   * Whether some view method hands this type back, which is what makes it a row a menu is drawn on.
   */
  private boolean returnedByAView(final ValueObject row) {
    Resource _eResource = row.eResource();
    ResourceSet _resourceSet = null;
    if (_eResource!=null) {
      _resourceSet=_eResource.getResourceSet();
    }
    final ResourceSet resourceSet = _resourceSet;
    if ((resourceSet == null)) {
      return false;
    }
    EList<Resource> _resources = resourceSet.getResources();
    for (final Resource resource : _resources) {
      {
        final TreeIterator<EObject> contents = resource.getAllContents();
        while (contents.hasNext()) {
          {
            final EObject next = contents.next();
            if ((next instanceof View)) {
              List<Method> _nullSafe = CqrsCollectionExtensions.<Method>nullSafe(((View)next).getMethods());
              for (final Method method : _nullSafe) {
                {
                  final ReturnType returns = method.getReturnType();
                  GenericArgs _generics = null;
                  if (returns!=null) {
                    _generics=returns.getGenerics();
                  }
                  final GenericArgs generics = _generics;
                  Type _xifexpression = null;
                  if (((generics != null) && (!generics.getArgs().isEmpty()))) {
                    _xifexpression = generics.getArgs().get(0);
                  } else {
                    Type _type = null;
                    if (returns!=null) {
                      _type=returns.getType();
                    }
                    _xifexpression = _type;
                  }
                  final Type returned = _xifexpression;
                  if ((returned == row)) {
                    return true;
                  }
                }
              }
            }
          }
        }
      }
    }
    return false;
  }

  /**
   * Every command in the model addressing the kind of thing this row identifies.
   * 
   * <p>Matched on the identifier's own type rather than on a name derived from it, because that is
   * exactly what the wire carries: a row's identity travels typed, and a client offers a command whose
   * target has the same type.
   */
  private List<Command> commandsAddressing(final Type idType, final ValueObject row) {
    final ArrayList<Command> found = new ArrayList<Command>();
    Resource _eResource = row.eResource();
    ResourceSet _resourceSet = null;
    if (_eResource!=null) {
      _resourceSet=_eResource.getResourceSet();
    }
    final ResourceSet resourceSet = _resourceSet;
    if ((resourceSet == null)) {
      return found;
    }
    EList<Resource> _resources = resourceSet.getResources();
    for (final Resource resource : _resources) {
      {
        final TreeIterator<EObject> contents = resource.getAllContents();
        while (contents.hasNext()) {
          {
            final EObject next = contents.next();
            if ((next instanceof Command)) {
              AbstractEntity _entity = CqrsEObjectExtensions.getEntity(((Command)next));
              AbstractEntityId _idType = null;
              if (_entity!=null) {
                _idType=CqrsAbstractEntityExtensions.getIdType(_entity);
              }
              boolean _tripleEquals = (_idType == idType);
              if (_tripleEquals) {
                found.add(((Command)next));
              }
            }
          }
        }
      }
    }
    return found;
  }

  /**
   * Names as a reader would list them: 'a', 'b' and 'c'.
   */
  private static String quoted(final List<String> names) {
    final Function1<String, String> _function = (String it) -> {
      return (("\'" + it) + "\'");
    };
    final List<String> quoted = IterableExtensions.<String>toList(ListExtensions.<String, String>map(names, _function));
    int _size = quoted.size();
    boolean _tripleEquals = (_size == 1);
    if (_tripleEquals) {
      return quoted.get(0);
    }
    int _size_1 = quoted.size();
    int _minus = (_size_1 - 1);
    String _join = IterableExtensions.join(quoted.subList(0, _minus), ", ");
    String _plus = (_join + " and ");
    int _size_2 = quoted.size();
    int _minus_1 = (_size_2 - 1);
    String _get = quoted.get(_minus_1);
    return (_plus + _get);
  }

  /**
   * Checks that a declared path is a shape a real identifier path could have.
   * 
   * <p>A path begins at an aggregate root and names the chain of children down to the thing it
   * addresses: 'ANNUAL_TRANSACTIONS 2026-a/TRANSACTION 45'. Three things follow, and all three are
   * mistakes a reader would otherwise only find when a path failed to validate at runtime - or never,
   * because nothing generated would have said so.
   * 
   * <p>An aggregate reached <em>inside</em> a composite identifier is not a step:
   * 'AnnualTransactionsId' is made of an account and a year, and the path still begins at
   * 'ANNUAL_TRANSACTIONS'. Writing the account as a first step is the mistake this catches most often,
   * because the prose of the model describes the pair as "the natural composite key (account, year)".
   */
  @Check
  public void checkEntityIdPathShape(final EntityIdPathType path) {
    Resource _eResource = path.eResource();
    URI _uRI = null;
    if (_eResource!=null) {
      _uRI=_eResource.getURI();
    }
    boolean _isArchived = CqrsModelArchives.isArchived(_uRI);
    if (_isArchived) {
      return;
    }
    final List<PathSegment> segments = CqrsCollectionExtensions.<PathSegment>nullSafe(path.getSegments());
    int _size = segments.size();
    boolean _lessThan = (_size < 2);
    if (_lessThan) {
      String _elvis = null;
      PathSegment _head = IterableExtensions.<PathSegment>head(segments);
      AbstractEntityId _type = null;
      if (_head!=null) {
        _type=_head.getType();
      }
      String _name = null;
      if (_type!=null) {
        _name=_type.getName();
      }
      if (_name != null) {
        _elvis = _name;
      } else {
        _elvis = "the identifier type";
      }
      String _plus = ("A path of one step is the identifier itself - use \'" + _elvis);
      String _plus_1 = (_plus + "\' rather than a path");
      this.error(_plus_1, path, CqrsDslPackage.Literals.ABSTRACT_ELEMENT__NAME, CqrsDslValidator.PATH_NEEDS_MORE_THAN_A_ROOT);
      return;
    }
    final AbstractEntityId first = IterableExtensions.<PathSegment>head(segments).getType();
    if (((first != null) && (!(first instanceof AggregateId)))) {
      String _name_1 = first.getName();
      String _plus_2 = ("A path starts at an aggregate root, and \'" + _name_1);
      String _plus_3 = (_plus_2 + "\' does not identify one");
      this.error(_plus_3, 
        IterableExtensions.<PathSegment>head(segments), CqrsDslPackage.Literals.PATH_SEGMENT__TYPE, CqrsDslValidator.PATH_MUST_START_AT_A_ROOT);
      return;
    }
    Aggregate _xifexpression = null;
    if ((first instanceof AggregateId)) {
      _xifexpression = ((AggregateId)first).getAggregate();
    } else {
      _xifexpression = null;
    }
    final Aggregate root = _xifexpression;
    Iterable<PathSegment> _drop = IterableExtensions.<PathSegment>drop(segments, 1);
    for (final PathSegment segment : _drop) {
      {
        final AbstractEntityId type = segment.getType();
        if ((type != null)) {
          if ((!(type instanceof EntityId))) {
            String _name_2 = type.getName();
            String _plus_4 = ("Only the first step is an aggregate; \'" + _name_2);
            String _plus_5 = (_plus_4 + "\' has to identify an entity of \'");
            String _elvis_1 = null;
            String _name_3 = null;
            if (root!=null) {
              _name_3=root.getName();
            }
            if (_name_3 != null) {
              _elvis_1 = _name_3;
            } else {
              _elvis_1 = "the root";
            }
            String _plus_6 = (_plus_5 + _elvis_1);
            String _plus_7 = (_plus_6 + "\'");
            this.error(_plus_7, segment, CqrsDslPackage.Literals.PATH_SEGMENT__TYPE, CqrsDslValidator.PATH_SEGMENT_NOT_OF_ROOT);
          } else {
            if ((root != null)) {
              final Entity entity = ((EntityId) type).getEntity();
              if ((((entity != null) && (entity.getRoot() != null)) && (entity.getRoot() != root))) {
                String _name_4 = entity.getName();
                String _plus_8 = ("\'" + _name_4);
                String _plus_9 = (_plus_8 + "\' belongs to \'");
                String _name_5 = entity.getRoot().getName();
                String _plus_10 = (_plus_9 + _name_5);
                String _plus_11 = (_plus_10 + "\', not to \'");
                String _name_6 = root.getName();
                String _plus_12 = (_plus_11 + _name_6);
                String _plus_13 = (_plus_12 + "\', so it cannot be a step of this path");
                this.error(_plus_13, segment, CqrsDslPackage.Literals.PATH_SEGMENT__TYPE, CqrsDslValidator.PATH_SEGMENT_NOT_OF_ROOT);
              }
            }
          }
        }
      }
    }
  }

  /**
   * Checks that a step's range can match something.
   * 
   * <p>Written out rather than marked with a symbol, because "may repeat" does not say whether the step
   * may also be absent - so the bounds are stated, and stated bounds can contradict each other. Caught
   * here rather than at runtime, where an impossible range silently rejects every path it is given.
   */
  @Check
  public void checkSegmentRange(final SegmentRange range) {
    Resource _eResource = range.eResource();
    URI _uRI = null;
    if (_eResource!=null) {
      _uRI=_eResource.getURI();
    }
    boolean _isArchived = CqrsModelArchives.isArchived(_uRI);
    if (_isArchived) {
      return;
    }
    boolean _isUnbounded = range.isUnbounded();
    if (_isUnbounded) {
      return;
    }
    int _max = range.getMax();
    boolean _lessThan = (_max < 1);
    if (_lessThan) {
      this.error("A step that accepts no identifier at all cannot be part of a path; leave it out instead", range, CqrsDslPackage.Literals.SEGMENT_RANGE__MAX, CqrsDslValidator.PATH_RANGE_INVALID);
    } else {
      int _max_1 = range.getMax();
      int _min = range.getMin();
      boolean _lessThan_1 = (_max_1 < _min);
      if (_lessThan_1) {
        int _min_1 = range.getMin();
        String _plus = ("The range is empty: at least " + Integer.valueOf(_min_1));
        String _plus_1 = (_plus + " but at most ");
        int _max_2 = range.getMax();
        String _plus_2 = (_plus_1 + Integer.valueOf(_max_2));
        this.error(_plus_2, range, CqrsDslPackage.Literals.SEGMENT_RANGE__MAX, CqrsDslValidator.PATH_RANGE_INVALID);
      }
    }
  }
}
