/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.fuin.dsl.cqrs.cqrsDsl.AbstractMethod;
import org.fuin.dsl.cqrs.cqrsDsl.BusinessRules;
import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.Event;
import org.fuin.dsl.cqrs.cqrsDsl.Parameter;
import org.fuin.dsl.cqrs.cqrsDsl.Preconditions;
import org.fuin.dsl.cqrs.cqrsDsl.Service;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Method</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getDoc <em>Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getPreconditions <em>Preconditions</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getBusinessRules <em>Business Rules</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getFiredEvents <em>Fired Events</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getOperationContext <em>Operation Context</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getServices <em>Services</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractMethodImpl#getEvents <em>Events</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AbstractMethodImpl extends MinimalEObjectImpl.Container implements AbstractMethod
{
  /**
   * The default value of the '{@link #getDoc() <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoc()
   * @generated
   * @ordered
   */
  protected static final String DOC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDoc() <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoc()
   * @generated
   * @ordered
   */
  protected String doc = DOC_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getPreconditions() <em>Preconditions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreconditions()
   * @generated
   * @ordered
   */
  protected Preconditions preconditions;

  /**
   * The cached value of the '{@link #getBusinessRules() <em>Business Rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBusinessRules()
   * @generated
   * @ordered
   */
  protected BusinessRules businessRules;

  /**
   * The cached value of the '{@link #getFiredEvents() <em>Fired Events</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFiredEvents()
   * @generated
   * @ordered
   */
  protected EList<Event> firedEvents;

  /**
   * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected EList<Parameter> parameters;

  /**
   * The cached value of the '{@link #getOperationContext() <em>Operation Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationContext()
   * @generated
   * @ordered
   */
  protected Service operationContext;

  /**
   * The cached value of the '{@link #getServices() <em>Services</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServices()
   * @generated
   * @ordered
   */
  protected EList<Service> services;

  /**
   * The cached value of the '{@link #getEvents() <em>Events</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvents()
   * @generated
   * @ordered
   */
  protected EList<Event> events;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.ABSTRACT_METHOD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDoc()
  {
    return doc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDoc(String newDoc)
  {
    String oldDoc = doc;
    doc = newDoc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ABSTRACT_METHOD__DOC, oldDoc, doc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ABSTRACT_METHOD__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Preconditions getPreconditions()
  {
    return preconditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPreconditions(Preconditions newPreconditions, NotificationChain msgs)
  {
    Preconditions oldPreconditions = preconditions;
    preconditions = newPreconditions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS, oldPreconditions, newPreconditions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPreconditions(Preconditions newPreconditions)
  {
    if (newPreconditions != preconditions)
    {
      NotificationChain msgs = null;
      if (preconditions != null)
        msgs = ((InternalEObject)preconditions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS, null, msgs);
      if (newPreconditions != null)
        msgs = ((InternalEObject)newPreconditions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS, null, msgs);
      msgs = basicSetPreconditions(newPreconditions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS, newPreconditions, newPreconditions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BusinessRules getBusinessRules()
  {
    return businessRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBusinessRules(BusinessRules newBusinessRules, NotificationChain msgs)
  {
    BusinessRules oldBusinessRules = businessRules;
    businessRules = newBusinessRules;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES, oldBusinessRules, newBusinessRules);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBusinessRules(BusinessRules newBusinessRules)
  {
    if (newBusinessRules != businessRules)
    {
      NotificationChain msgs = null;
      if (businessRules != null)
        msgs = ((InternalEObject)businessRules).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES, null, msgs);
      if (newBusinessRules != null)
        msgs = ((InternalEObject)newBusinessRules).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES, null, msgs);
      msgs = basicSetBusinessRules(newBusinessRules, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES, newBusinessRules, newBusinessRules));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Event> getFiredEvents()
  {
    if (firedEvents == null)
    {
      firedEvents = new EObjectResolvingEList<Event>(Event.class, this, CqrsDslPackage.ABSTRACT_METHOD__FIRED_EVENTS);
    }
    return firedEvents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Parameter> getParameters()
  {
    if (parameters == null)
    {
      parameters = new EObjectContainmentEList<Parameter>(Parameter.class, this, CqrsDslPackage.ABSTRACT_METHOD__PARAMETERS);
    }
    return parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Service getOperationContext()
  {
    if (operationContext != null && operationContext.eIsProxy())
    {
      InternalEObject oldOperationContext = (InternalEObject)operationContext;
      operationContext = (Service)eResolveProxy(oldOperationContext);
      if (operationContext != oldOperationContext)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CqrsDslPackage.ABSTRACT_METHOD__OPERATION_CONTEXT, oldOperationContext, operationContext));
      }
    }
    return operationContext;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Service basicGetOperationContext()
  {
    return operationContext;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperationContext(Service newOperationContext)
  {
    Service oldOperationContext = operationContext;
    operationContext = newOperationContext;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ABSTRACT_METHOD__OPERATION_CONTEXT, oldOperationContext, operationContext));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Service> getServices()
  {
    if (services == null)
    {
      services = new EObjectContainmentEList<Service>(Service.class, this, CqrsDslPackage.ABSTRACT_METHOD__SERVICES);
    }
    return services;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Event> getEvents()
  {
    if (events == null)
    {
      events = new EObjectContainmentEList<Event>(Event.class, this, CqrsDslPackage.ABSTRACT_METHOD__EVENTS);
    }
    return events;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS:
        return basicSetPreconditions(null, msgs);
      case CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES:
        return basicSetBusinessRules(null, msgs);
      case CqrsDslPackage.ABSTRACT_METHOD__PARAMETERS:
        return ((InternalEList<?>)getParameters()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.ABSTRACT_METHOD__SERVICES:
        return ((InternalEList<?>)getServices()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.ABSTRACT_METHOD__EVENTS:
        return ((InternalEList<?>)getEvents()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_METHOD__DOC:
        return getDoc();
      case CqrsDslPackage.ABSTRACT_METHOD__NAME:
        return getName();
      case CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS:
        return getPreconditions();
      case CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES:
        return getBusinessRules();
      case CqrsDslPackage.ABSTRACT_METHOD__FIRED_EVENTS:
        return getFiredEvents();
      case CqrsDslPackage.ABSTRACT_METHOD__PARAMETERS:
        return getParameters();
      case CqrsDslPackage.ABSTRACT_METHOD__OPERATION_CONTEXT:
        if (resolve) return getOperationContext();
        return basicGetOperationContext();
      case CqrsDslPackage.ABSTRACT_METHOD__SERVICES:
        return getServices();
      case CqrsDslPackage.ABSTRACT_METHOD__EVENTS:
        return getEvents();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_METHOD__DOC:
        setDoc((String)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__NAME:
        setName((String)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS:
        setPreconditions((Preconditions)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES:
        setBusinessRules((BusinessRules)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__FIRED_EVENTS:
        getFiredEvents().clear();
        getFiredEvents().addAll((Collection<? extends Event>)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__PARAMETERS:
        getParameters().clear();
        getParameters().addAll((Collection<? extends Parameter>)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__OPERATION_CONTEXT:
        setOperationContext((Service)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__SERVICES:
        getServices().clear();
        getServices().addAll((Collection<? extends Service>)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__EVENTS:
        getEvents().clear();
        getEvents().addAll((Collection<? extends Event>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_METHOD__DOC:
        setDoc(DOC_EDEFAULT);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS:
        setPreconditions((Preconditions)null);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES:
        setBusinessRules((BusinessRules)null);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__FIRED_EVENTS:
        getFiredEvents().clear();
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__PARAMETERS:
        getParameters().clear();
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__OPERATION_CONTEXT:
        setOperationContext((Service)null);
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__SERVICES:
        getServices().clear();
        return;
      case CqrsDslPackage.ABSTRACT_METHOD__EVENTS:
        getEvents().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_METHOD__DOC:
        return DOC_EDEFAULT == null ? doc != null : !DOC_EDEFAULT.equals(doc);
      case CqrsDslPackage.ABSTRACT_METHOD__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CqrsDslPackage.ABSTRACT_METHOD__PRECONDITIONS:
        return preconditions != null;
      case CqrsDslPackage.ABSTRACT_METHOD__BUSINESS_RULES:
        return businessRules != null;
      case CqrsDslPackage.ABSTRACT_METHOD__FIRED_EVENTS:
        return firedEvents != null && !firedEvents.isEmpty();
      case CqrsDslPackage.ABSTRACT_METHOD__PARAMETERS:
        return parameters != null && !parameters.isEmpty();
      case CqrsDslPackage.ABSTRACT_METHOD__OPERATION_CONTEXT:
        return operationContext != null;
      case CqrsDslPackage.ABSTRACT_METHOD__SERVICES:
        return services != null && !services.isEmpty();
      case CqrsDslPackage.ABSTRACT_METHOD__EVENTS:
        return events != null && !events.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (doc: ");
    result.append(doc);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //AbstractMethodImpl
