/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.fuin.dsl.cqrs.cqrsDsl.Attribute;
import org.fuin.dsl.cqrs.cqrsDsl.CollisionStrategy;
import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.Key;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Key</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.KeyImpl#getKeyAttributes <em>Key Attributes</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.KeyImpl#getOnCollision <em>On Collision</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.KeyImpl#getDisplayAs <em>Display As</em>}</li>
 * </ul>
 *
 * @generated
 */
public class KeyImpl extends AbstractBusinessRuleImpl implements Key
{
  /**
   * The cached value of the '{@link #getKeyAttributes() <em>Key Attributes</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyAttributes()
   * @generated
   * @ordered
   */
  protected EList<Attribute> keyAttributes;

  /**
   * The default value of the '{@link #getOnCollision() <em>On Collision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOnCollision()
   * @generated
   * @ordered
   */
  protected static final CollisionStrategy ON_COLLISION_EDEFAULT = CollisionStrategy.REFUSE;

  /**
   * The cached value of the '{@link #getOnCollision() <em>On Collision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOnCollision()
   * @generated
   * @ordered
   */
  protected CollisionStrategy onCollision = ON_COLLISION_EDEFAULT;

  /**
   * The default value of the '{@link #getDisplayAs() <em>Display As</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplayAs()
   * @generated
   * @ordered
   */
  protected static final String DISPLAY_AS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDisplayAs() <em>Display As</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplayAs()
   * @generated
   * @ordered
   */
  protected String displayAs = DISPLAY_AS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected KeyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.KEY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Attribute> getKeyAttributes()
  {
    if (keyAttributes == null)
    {
      keyAttributes = new EObjectResolvingEList<Attribute>(Attribute.class, this, CqrsDslPackage.KEY__KEY_ATTRIBUTES);
    }
    return keyAttributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CollisionStrategy getOnCollision()
  {
    return onCollision;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOnCollision(CollisionStrategy newOnCollision)
  {
    CollisionStrategy oldOnCollision = onCollision;
    onCollision = newOnCollision == null ? ON_COLLISION_EDEFAULT : newOnCollision;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.KEY__ON_COLLISION, oldOnCollision, onCollision));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDisplayAs()
  {
    return displayAs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDisplayAs(String newDisplayAs)
  {
    String oldDisplayAs = displayAs;
    displayAs = newDisplayAs;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.KEY__DISPLAY_AS, oldDisplayAs, displayAs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CqrsDslPackage.KEY__KEY_ATTRIBUTES:
        return getKeyAttributes();
      case CqrsDslPackage.KEY__ON_COLLISION:
        return getOnCollision();
      case CqrsDslPackage.KEY__DISPLAY_AS:
        return getDisplayAs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CqrsDslPackage.KEY__KEY_ATTRIBUTES:
        getKeyAttributes().clear();
        getKeyAttributes().addAll((Collection<? extends Attribute>)newValue);
        return;
      case CqrsDslPackage.KEY__ON_COLLISION:
        setOnCollision((CollisionStrategy)newValue);
        return;
      case CqrsDslPackage.KEY__DISPLAY_AS:
        setDisplayAs((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.KEY__KEY_ATTRIBUTES:
        getKeyAttributes().clear();
        return;
      case CqrsDslPackage.KEY__ON_COLLISION:
        setOnCollision(ON_COLLISION_EDEFAULT);
        return;
      case CqrsDslPackage.KEY__DISPLAY_AS:
        setDisplayAs(DISPLAY_AS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.KEY__KEY_ATTRIBUTES:
        return keyAttributes != null && !keyAttributes.isEmpty();
      case CqrsDslPackage.KEY__ON_COLLISION:
        return onCollision != ON_COLLISION_EDEFAULT;
      case CqrsDslPackage.KEY__DISPLAY_AS:
        return DISPLAY_AS_EDEFAULT == null ? displayAs != null : !DISPLAY_AS_EDEFAULT.equals(displayAs);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (onCollision: ");
    result.append(onCollision);
    result.append(", displayAs: ");
    result.append(displayAs);
    result.append(')');
    return result.toString();
  }

} //KeyImpl
