/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.Hint;
import org.fuin.dsl.cqrs.cqrsDsl.Method;
import org.fuin.dsl.cqrs.cqrsDsl.ReturnType;
import org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Method</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.MethodImpl#getRefMethod <em>Ref Method</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.MethodImpl#getRestPath <em>Rest Path</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.MethodImpl#getMetaInfo <em>Meta Info</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.MethodImpl#getHints <em>Hints</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.MethodImpl#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MethodImpl extends AbstractMethodImpl implements Method
{
  /**
   * The cached value of the '{@link #getRefMethod() <em>Ref Method</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefMethod()
   * @generated
   * @ordered
   */
  protected Method refMethod;

  /**
   * The default value of the '{@link #getRestPath() <em>Rest Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRestPath()
   * @generated
   * @ordered
   */
  protected static final String REST_PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRestPath() <em>Rest Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRestPath()
   * @generated
   * @ordered
   */
  protected String restPath = REST_PATH_EDEFAULT;

  /**
   * The cached value of the '{@link #getMetaInfo() <em>Meta Info</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMetaInfo()
   * @generated
   * @ordered
   */
  protected TypeMetaInfo metaInfo;

  /**
   * The cached value of the '{@link #getHints() <em>Hints</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHints()
   * @generated
   * @ordered
   */
  protected EList<Hint> hints;

  /**
   * The cached value of the '{@link #getReturnType() <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturnType()
   * @generated
   * @ordered
   */
  protected ReturnType returnType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.METHOD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Method getRefMethod()
  {
    if (refMethod != null && refMethod.eIsProxy())
    {
      InternalEObject oldRefMethod = (InternalEObject)refMethod;
      refMethod = (Method)eResolveProxy(oldRefMethod);
      if (refMethod != oldRefMethod)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CqrsDslPackage.METHOD__REF_METHOD, oldRefMethod, refMethod));
      }
    }
    return refMethod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Method basicGetRefMethod()
  {
    return refMethod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefMethod(Method newRefMethod)
  {
    Method oldRefMethod = refMethod;
    refMethod = newRefMethod;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.METHOD__REF_METHOD, oldRefMethod, refMethod));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRestPath()
  {
    return restPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRestPath(String newRestPath)
  {
    String oldRestPath = restPath;
    restPath = newRestPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.METHOD__REST_PATH, oldRestPath, restPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeMetaInfo getMetaInfo()
  {
    return metaInfo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMetaInfo(TypeMetaInfo newMetaInfo, NotificationChain msgs)
  {
    TypeMetaInfo oldMetaInfo = metaInfo;
    metaInfo = newMetaInfo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CqrsDslPackage.METHOD__META_INFO, oldMetaInfo, newMetaInfo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMetaInfo(TypeMetaInfo newMetaInfo)
  {
    if (newMetaInfo != metaInfo)
    {
      NotificationChain msgs = null;
      if (metaInfo != null)
        msgs = ((InternalEObject)metaInfo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.METHOD__META_INFO, null, msgs);
      if (newMetaInfo != null)
        msgs = ((InternalEObject)newMetaInfo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.METHOD__META_INFO, null, msgs);
      msgs = basicSetMetaInfo(newMetaInfo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.METHOD__META_INFO, newMetaInfo, newMetaInfo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Hint> getHints()
  {
    if (hints == null)
    {
      hints = new EObjectContainmentEList<Hint>(Hint.class, this, CqrsDslPackage.METHOD__HINTS);
    }
    return hints;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReturnType getReturnType()
  {
    return returnType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReturnType(ReturnType newReturnType, NotificationChain msgs)
  {
    ReturnType oldReturnType = returnType;
    returnType = newReturnType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CqrsDslPackage.METHOD__RETURN_TYPE, oldReturnType, newReturnType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReturnType(ReturnType newReturnType)
  {
    if (newReturnType != returnType)
    {
      NotificationChain msgs = null;
      if (returnType != null)
        msgs = ((InternalEObject)returnType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.METHOD__RETURN_TYPE, null, msgs);
      if (newReturnType != null)
        msgs = ((InternalEObject)newReturnType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.METHOD__RETURN_TYPE, null, msgs);
      msgs = basicSetReturnType(newReturnType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.METHOD__RETURN_TYPE, newReturnType, newReturnType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CqrsDslPackage.METHOD__META_INFO:
        return basicSetMetaInfo(null, msgs);
      case CqrsDslPackage.METHOD__HINTS:
        return ((InternalEList<?>)getHints()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.METHOD__RETURN_TYPE:
        return basicSetReturnType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CqrsDslPackage.METHOD__REF_METHOD:
        if (resolve) return getRefMethod();
        return basicGetRefMethod();
      case CqrsDslPackage.METHOD__REST_PATH:
        return getRestPath();
      case CqrsDslPackage.METHOD__META_INFO:
        return getMetaInfo();
      case CqrsDslPackage.METHOD__HINTS:
        return getHints();
      case CqrsDslPackage.METHOD__RETURN_TYPE:
        return getReturnType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CqrsDslPackage.METHOD__REF_METHOD:
        setRefMethod((Method)newValue);
        return;
      case CqrsDslPackage.METHOD__REST_PATH:
        setRestPath((String)newValue);
        return;
      case CqrsDslPackage.METHOD__META_INFO:
        setMetaInfo((TypeMetaInfo)newValue);
        return;
      case CqrsDslPackage.METHOD__HINTS:
        getHints().clear();
        getHints().addAll((Collection<? extends Hint>)newValue);
        return;
      case CqrsDslPackage.METHOD__RETURN_TYPE:
        setReturnType((ReturnType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.METHOD__REF_METHOD:
        setRefMethod((Method)null);
        return;
      case CqrsDslPackage.METHOD__REST_PATH:
        setRestPath(REST_PATH_EDEFAULT);
        return;
      case CqrsDslPackage.METHOD__META_INFO:
        setMetaInfo((TypeMetaInfo)null);
        return;
      case CqrsDslPackage.METHOD__HINTS:
        getHints().clear();
        return;
      case CqrsDslPackage.METHOD__RETURN_TYPE:
        setReturnType((ReturnType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.METHOD__REF_METHOD:
        return refMethod != null;
      case CqrsDslPackage.METHOD__REST_PATH:
        return REST_PATH_EDEFAULT == null ? restPath != null : !REST_PATH_EDEFAULT.equals(restPath);
      case CqrsDslPackage.METHOD__META_INFO:
        return metaInfo != null;
      case CqrsDslPackage.METHOD__HINTS:
        return hints != null && !hints.isEmpty();
      case CqrsDslPackage.METHOD__RETURN_TYPE:
        return returnType != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (restPath: ");
    result.append(restPath);
    result.append(')');
    return result.toString();
  }

} //MethodImpl
