/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.fuin.dsl.cqrs.cqrsDsl.BusinessRule;
import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.Hint;
import org.fuin.dsl.cqrs.cqrsDsl.Method;
import org.fuin.dsl.cqrs.cqrsDsl.Projection;
import org.fuin.dsl.cqrs.cqrsDsl.View;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>View</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.ViewImpl#getProjection <em>Projection</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.ViewImpl#getHints <em>Hints</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.ViewImpl#getRestPath <em>Rest Path</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.ViewImpl#getCron <em>Cron</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.ViewImpl#getBusinessRules <em>Business Rules</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.ViewImpl#getMethods <em>Methods</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ViewImpl extends AbstractElementImpl implements View
{
  /**
   * The cached value of the '{@link #getProjection() <em>Projection</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjection()
   * @generated
   * @ordered
   */
  protected Projection projection;

  /**
   * The cached value of the '{@link #getHints() <em>Hints</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHints()
   * @generated
   * @ordered
   */
  protected EList<Hint> hints;

  /**
   * The default value of the '{@link #getRestPath() <em>Rest Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRestPath()
   * @generated
   * @ordered
   */
  protected static final String REST_PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRestPath() <em>Rest Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRestPath()
   * @generated
   * @ordered
   */
  protected String restPath = REST_PATH_EDEFAULT;

  /**
   * The default value of the '{@link #getCron() <em>Cron</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCron()
   * @generated
   * @ordered
   */
  protected static final String CRON_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCron() <em>Cron</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCron()
   * @generated
   * @ordered
   */
  protected String cron = CRON_EDEFAULT;

  /**
   * The cached value of the '{@link #getBusinessRules() <em>Business Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBusinessRules()
   * @generated
   * @ordered
   */
  protected EList<BusinessRule> businessRules;

  /**
   * The cached value of the '{@link #getMethods() <em>Methods</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethods()
   * @generated
   * @ordered
   */
  protected EList<Method> methods;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ViewImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.VIEW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Projection getProjection()
  {
    if (projection != null && projection.eIsProxy())
    {
      InternalEObject oldProjection = (InternalEObject)projection;
      projection = (Projection)eResolveProxy(oldProjection);
      if (projection != oldProjection)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CqrsDslPackage.VIEW__PROJECTION, oldProjection, projection));
      }
    }
    return projection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Projection basicGetProjection()
  {
    return projection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProjection(Projection newProjection)
  {
    Projection oldProjection = projection;
    projection = newProjection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.VIEW__PROJECTION, oldProjection, projection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Hint> getHints()
  {
    if (hints == null)
    {
      hints = new EObjectContainmentEList<Hint>(Hint.class, this, CqrsDslPackage.VIEW__HINTS);
    }
    return hints;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRestPath()
  {
    return restPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRestPath(String newRestPath)
  {
    String oldRestPath = restPath;
    restPath = newRestPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.VIEW__REST_PATH, oldRestPath, restPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCron()
  {
    return cron;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCron(String newCron)
  {
    String oldCron = cron;
    cron = newCron;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.VIEW__CRON, oldCron, cron));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BusinessRule> getBusinessRules()
  {
    if (businessRules == null)
    {
      businessRules = new EObjectContainmentEList<BusinessRule>(BusinessRule.class, this, CqrsDslPackage.VIEW__BUSINESS_RULES);
    }
    return businessRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Method> getMethods()
  {
    if (methods == null)
    {
      methods = new EObjectContainmentEList<Method>(Method.class, this, CqrsDslPackage.VIEW__METHODS);
    }
    return methods;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CqrsDslPackage.VIEW__HINTS:
        return ((InternalEList<?>)getHints()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.VIEW__BUSINESS_RULES:
        return ((InternalEList<?>)getBusinessRules()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.VIEW__METHODS:
        return ((InternalEList<?>)getMethods()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CqrsDslPackage.VIEW__PROJECTION:
        if (resolve) return getProjection();
        return basicGetProjection();
      case CqrsDslPackage.VIEW__HINTS:
        return getHints();
      case CqrsDslPackage.VIEW__REST_PATH:
        return getRestPath();
      case CqrsDslPackage.VIEW__CRON:
        return getCron();
      case CqrsDslPackage.VIEW__BUSINESS_RULES:
        return getBusinessRules();
      case CqrsDslPackage.VIEW__METHODS:
        return getMethods();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CqrsDslPackage.VIEW__PROJECTION:
        setProjection((Projection)newValue);
        return;
      case CqrsDslPackage.VIEW__HINTS:
        getHints().clear();
        getHints().addAll((Collection<? extends Hint>)newValue);
        return;
      case CqrsDslPackage.VIEW__REST_PATH:
        setRestPath((String)newValue);
        return;
      case CqrsDslPackage.VIEW__CRON:
        setCron((String)newValue);
        return;
      case CqrsDslPackage.VIEW__BUSINESS_RULES:
        getBusinessRules().clear();
        getBusinessRules().addAll((Collection<? extends BusinessRule>)newValue);
        return;
      case CqrsDslPackage.VIEW__METHODS:
        getMethods().clear();
        getMethods().addAll((Collection<? extends Method>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.VIEW__PROJECTION:
        setProjection((Projection)null);
        return;
      case CqrsDslPackage.VIEW__HINTS:
        getHints().clear();
        return;
      case CqrsDslPackage.VIEW__REST_PATH:
        setRestPath(REST_PATH_EDEFAULT);
        return;
      case CqrsDslPackage.VIEW__CRON:
        setCron(CRON_EDEFAULT);
        return;
      case CqrsDslPackage.VIEW__BUSINESS_RULES:
        getBusinessRules().clear();
        return;
      case CqrsDslPackage.VIEW__METHODS:
        getMethods().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.VIEW__PROJECTION:
        return projection != null;
      case CqrsDslPackage.VIEW__HINTS:
        return hints != null && !hints.isEmpty();
      case CqrsDslPackage.VIEW__REST_PATH:
        return REST_PATH_EDEFAULT == null ? restPath != null : !REST_PATH_EDEFAULT.equals(restPath);
      case CqrsDslPackage.VIEW__CRON:
        return CRON_EDEFAULT == null ? cron != null : !CRON_EDEFAULT.equals(cron);
      case CqrsDslPackage.VIEW__BUSINESS_RULES:
        return businessRules != null && !businessRules.isEmpty();
      case CqrsDslPackage.VIEW__METHODS:
        return methods != null && !methods.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (restPath: ");
    result.append(restPath);
    result.append(", cron: ");
    result.append(cron);
    result.append(')');
    return result.toString();
  }

} //ViewImpl
