/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Business Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractBusinessRule#getException <em>Exception</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractBusinessRule#getConsistency <em>Consistency</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAbstractBusinessRule()
 * @model
 * @generated
 */
public interface AbstractBusinessRule extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Exception</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exception</em>' reference.
   * @see #setException(org.fuin.dsl.cqrs.cqrsDsl.Exception)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAbstractBusinessRule_Exception()
   * @model
   * @generated
   */
  org.fuin.dsl.cqrs.cqrsDsl.Exception getException();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractBusinessRule#getException <em>Exception</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exception</em>' reference.
   * @see #getException()
   * @generated
   */
  void setException(org.fuin.dsl.cqrs.cqrsDsl.Exception value);

  /**
   * Returns the value of the '<em><b>Consistency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consistency</em>' containment reference.
   * @see #setConsistency(Consistency)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAbstractBusinessRule_Consistency()
   * @model containment="true"
   * @generated
   */
  Consistency getConsistency();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractBusinessRule#getConsistency <em>Consistency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consistency</em>' containment reference.
   * @see #getConsistency()
   * @generated
   */
  void setConsistency(Consistency value);

} // AbstractBusinessRule
