/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aggregate Id</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.AggregateId#getAggregate <em>Aggregate</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAggregateId()
 * @model
 * @generated
 */
public interface AggregateId extends AbstractEntityId
{
  /**
   * Returns the value of the '<em><b>Aggregate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aggregate</em>' reference.
   * @see #setAggregate(Aggregate)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAggregateId_Aggregate()
   * @model
   * @generated
   */
  Aggregate getAggregate();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.AggregateId#getAggregate <em>Aggregate</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aggregate</em>' reference.
   * @see #getAggregate()
   * @generated
   */
  void setAggregate(Aggregate value);

} // AggregateId
