/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Protection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getLevelDoc <em>Level Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getLevel <em>Level</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getCategoryDoc <em>Category Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getCategories <em>Categories</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getSubjectDoc <em>Subject Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getPurposeDoc <em>Purpose Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getPurpose <em>Purpose</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getBasisDoc <em>Basis Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getLawfulBasis <em>Lawful Basis</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getRetentionDoc <em>Retention Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getRetention <em>Retention</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getErasure <em>Erasure</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection()
 * @model
 * @generated
 */
public interface DataProtection extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Level Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level Doc</em>' attribute.
   * @see #setLevelDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_LevelDoc()
   * @model
   * @generated
   */
  String getLevelDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getLevelDoc <em>Level Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level Doc</em>' attribute.
   * @see #getLevelDoc()
   * @generated
   */
  void setLevelDoc(String value);

  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * The literals are from the enumeration {@link org.fuin.dsl.cqrs.cqrsDsl.ProtectionLevel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.ProtectionLevel
   * @see #setLevel(ProtectionLevel)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_Level()
   * @model
   * @generated
   */
  ProtectionLevel getLevel();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.ProtectionLevel
   * @see #getLevel()
   * @generated
   */
  void setLevel(ProtectionLevel value);

  /**
   * Returns the value of the '<em><b>Category Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Category Doc</em>' attribute.
   * @see #setCategoryDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_CategoryDoc()
   * @model
   * @generated
   */
  String getCategoryDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getCategoryDoc <em>Category Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Category Doc</em>' attribute.
   * @see #getCategoryDoc()
   * @generated
   */
  void setCategoryDoc(String value);

  /**
   * Returns the value of the '<em><b>Categories</b></em>' attribute list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.SpecialCategory}.
   * The literals are from the enumeration {@link org.fuin.dsl.cqrs.cqrsDsl.SpecialCategory}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Categories</em>' attribute list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.SpecialCategory
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_Categories()
   * @model unique="false"
   * @generated
   */
  EList<SpecialCategory> getCategories();

  /**
   * Returns the value of the '<em><b>Subject Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject Doc</em>' attribute.
   * @see #setSubjectDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_SubjectDoc()
   * @model
   * @generated
   */
  String getSubjectDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getSubjectDoc <em>Subject Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject Doc</em>' attribute.
   * @see #getSubjectDoc()
   * @generated
   */
  void setSubjectDoc(String value);

  /**
   * Returns the value of the '<em><b>Subject</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject</em>' attribute.
   * @see #setSubject(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_Subject()
   * @model
   * @generated
   */
  String getSubject();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getSubject <em>Subject</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject</em>' attribute.
   * @see #getSubject()
   * @generated
   */
  void setSubject(String value);

  /**
   * Returns the value of the '<em><b>Purpose Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Purpose Doc</em>' attribute.
   * @see #setPurposeDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_PurposeDoc()
   * @model
   * @generated
   */
  String getPurposeDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getPurposeDoc <em>Purpose Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Purpose Doc</em>' attribute.
   * @see #getPurposeDoc()
   * @generated
   */
  void setPurposeDoc(String value);

  /**
   * Returns the value of the '<em><b>Purpose</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Purpose</em>' attribute.
   * @see #setPurpose(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_Purpose()
   * @model
   * @generated
   */
  String getPurpose();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getPurpose <em>Purpose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Purpose</em>' attribute.
   * @see #getPurpose()
   * @generated
   */
  void setPurpose(String value);

  /**
   * Returns the value of the '<em><b>Basis Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basis Doc</em>' attribute.
   * @see #setBasisDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_BasisDoc()
   * @model
   * @generated
   */
  String getBasisDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getBasisDoc <em>Basis Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basis Doc</em>' attribute.
   * @see #getBasisDoc()
   * @generated
   */
  void setBasisDoc(String value);

  /**
   * Returns the value of the '<em><b>Lawful Basis</b></em>' attribute.
   * The literals are from the enumeration {@link org.fuin.dsl.cqrs.cqrsDsl.LawfulBasis}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lawful Basis</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.LawfulBasis
   * @see #setLawfulBasis(LawfulBasis)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_LawfulBasis()
   * @model
   * @generated
   */
  LawfulBasis getLawfulBasis();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getLawfulBasis <em>Lawful Basis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lawful Basis</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.LawfulBasis
   * @see #getLawfulBasis()
   * @generated
   */
  void setLawfulBasis(LawfulBasis value);

  /**
   * Returns the value of the '<em><b>Retention Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retention Doc</em>' attribute.
   * @see #setRetentionDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_RetentionDoc()
   * @model
   * @generated
   */
  String getRetentionDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getRetentionDoc <em>Retention Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Retention Doc</em>' attribute.
   * @see #getRetentionDoc()
   * @generated
   */
  void setRetentionDoc(String value);

  /**
   * Returns the value of the '<em><b>Retention</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retention</em>' containment reference.
   * @see #setRetention(Duration)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_Retention()
   * @model containment="true"
   * @generated
   */
  Duration getRetention();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getRetention <em>Retention</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Retention</em>' containment reference.
   * @see #getRetention()
   * @generated
   */
  void setRetention(Duration value);

  /**
   * Returns the value of the '<em><b>Erasure</b></em>' attribute.
   * The literals are from the enumeration {@link org.fuin.dsl.cqrs.cqrsDsl.ErasureStrategy}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Erasure</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.ErasureStrategy
   * @see #setErasure(ErasureStrategy)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDataProtection_Erasure()
   * @model
   * @generated
   */
  ErasureStrategy getErasure();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.DataProtection#getErasure <em>Erasure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Erasure</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.ErasureStrategy
   * @see #getErasure()
   * @generated
   */
  void setErasure(ErasureStrategy value);

} // DataProtection
