/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identity Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getIdentityArgument()
 * @model
 * @generated
 */
public interface IdentityArgument extends RuleArgument
{
} // IdentityArgument
