/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Overridden Type Meta Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.OverriddenTypeMetaInfo#getMetaInfo <em>Meta Info</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.OverriddenTypeMetaInfo#getHints <em>Hints</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getOverriddenTypeMetaInfo()
 * @model
 * @generated
 */
public interface OverriddenTypeMetaInfo extends EObject
{
  /**
   * Returns the value of the '<em><b>Meta Info</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Meta Info</em>' containment reference.
   * @see #setMetaInfo(TypeMetaInfo)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getOverriddenTypeMetaInfo_MetaInfo()
   * @model containment="true"
   * @generated
   */
  TypeMetaInfo getMetaInfo();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.OverriddenTypeMetaInfo#getMetaInfo <em>Meta Info</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Meta Info</em>' containment reference.
   * @see #getMetaInfo()
   * @generated
   */
  void setMetaInfo(TypeMetaInfo value);

  /**
   * Returns the value of the '<em><b>Hints</b></em>' containment reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Hint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hints</em>' containment reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getOverriddenTypeMetaInfo_Hints()
   * @model containment="true"
   * @generated
   */
  EList<Hint> getHints();

} // OverriddenTypeMetaInfo
