/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Is Empty</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.RuleIsEmpty#getLeft <em>Left</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getRuleIsEmpty()
 * @model
 * @generated
 */
public interface RuleIsEmpty extends RuleExpr
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(RuleAttrRef)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getRuleIsEmpty_Left()
   * @model containment="true"
   * @generated
   */
  RuleAttrRef getLeft();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.RuleIsEmpty#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(RuleAttrRef value);

} // RuleIsEmpty
