/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Or</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.RuleOr#getLeft <em>Left</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.RuleOr#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getRuleOr()
 * @model
 * @generated
 */
public interface RuleOr extends RuleExpr
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(RuleExpr)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getRuleOr_Left()
   * @model containment="true"
   * @generated
   */
  RuleExpr getLeft();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.RuleOr#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(RuleExpr value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(RuleExpr)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getRuleOr_Right()
   * @model containment="true"
   * @generated
   */
  RuleExpr getRight();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.RuleOr#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(RuleExpr value);

} // RuleOr
