/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract VO</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractVO#getBase <em>Base</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractVO#getConstructors <em>Constructors</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractVO#getMethods <em>Methods</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAbstractVO()
 * @model
 * @generated
 */
public interface AbstractVO extends InternalType
{
  /**
   * Returns the value of the '<em><b>Base</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' reference.
   * @see #setBase(ExternalType)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAbstractVO_Base()
   * @model
   * @generated
   */
  ExternalType getBase();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.AbstractVO#getBase <em>Base</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' reference.
   * @see #getBase()
   * @generated
   */
  void setBase(ExternalType value);

  /**
   * Returns the value of the '<em><b>Constructors</b></em>' containment reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Constructor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constructors</em>' containment reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAbstractVO_Constructors()
   * @model containment="true"
   * @generated
   */
  EList<Constructor> getConstructors();

  /**
   * Returns the value of the '<em><b>Methods</b></em>' containment reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Method}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methods</em>' containment reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAbstractVO_Methods()
   * @model containment="true"
   * @generated
   */
  EList<Method> getMethods();

} // AbstractVO
