/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Attribute#getInvariants <em>Invariants</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends Variable
{
  /**
   * Returns the value of the '<em><b>Invariants</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invariants</em>' containment reference.
   * @see #setInvariants(Invariants)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getAttribute_Invariants()
   * @model containment="true"
   * @generated
   */
  Invariants getInvariants();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Attribute#getInvariants <em>Invariants</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invariants</em>' containment reference.
   * @see #getInvariants()
   * @generated
   */
  void setInvariants(Invariants value);

} // Attribute
