/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command Handler</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.CommandHandler#getCommands <em>Commands</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.CommandHandler#getAggregates <em>Aggregates</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getCommandHandler()
 * @model
 * @generated
 */
public interface CommandHandler extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Commands</b></em>' reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Command}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getCommandHandler_Commands()
   * @model
   * @generated
   */
  EList<Command> getCommands();

  /**
   * Returns the value of the '<em><b>Aggregates</b></em>' reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Aggregate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aggregates</em>' reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getCommandHandler_Aggregates()
   * @model
   * @generated
   */
  EList<Aggregate> getAggregates();

} // CommandHandler
