/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Consistency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Consistency#getDoc <em>Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Consistency#getLevel <em>Level</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Consistency#getWeakConsistency <em>Weak Consistency</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConsistency()
 * @model
 * @generated
 */
public interface Consistency extends EObject
{
  /**
   * Returns the value of the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc</em>' attribute.
   * @see #setDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConsistency_Doc()
   * @model
   * @generated
   */
  String getDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Consistency#getDoc <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc</em>' attribute.
   * @see #getDoc()
   * @generated
   */
  void setDoc(String value);

  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * The literals are from the enumeration {@link org.fuin.dsl.cqrs.cqrsDsl.ConsistencyLevel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.ConsistencyLevel
   * @see #setLevel(ConsistencyLevel)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConsistency_Level()
   * @model
   * @generated
   */
  ConsistencyLevel getLevel();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Consistency#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see org.fuin.dsl.cqrs.cqrsDsl.ConsistencyLevel
   * @see #getLevel()
   * @generated
   */
  void setLevel(ConsistencyLevel value);

  /**
   * Returns the value of the '<em><b>Weak Consistency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weak Consistency</em>' containment reference.
   * @see #setWeakConsistency(WeakConsistency)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConsistency_WeakConsistency()
   * @model containment="true"
   * @generated
   */
  WeakConsistency getWeakConsistency();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Consistency#getWeakConsistency <em>Weak Consistency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weak Consistency</em>' containment reference.
   * @see #getWeakConsistency()
   * @generated
   */
  void setWeakConsistency(WeakConsistency value);

} // Consistency
