/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Constraint#getInput <em>Input</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Constraint#getException <em>Exception</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Constraint#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Constraint#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Input</b></em>' reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConstraint_Input()
   * @model
   * @generated
   */
  EList<Type> getInput();

  /**
   * Returns the value of the '<em><b>Exception</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exception</em>' reference.
   * @see #setException(org.fuin.dsl.cqrs.cqrsDsl.Exception)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConstraint_Exception()
   * @model
   * @generated
   */
  org.fuin.dsl.cqrs.cqrsDsl.Exception getException();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Constraint#getException <em>Exception</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exception</em>' reference.
   * @see #getException()
   * @generated
   */
  void setException(org.fuin.dsl.cqrs.cqrsDsl.Exception value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConstraint_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getConstraint_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Constraint#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

} // Constraint
