/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Dependency#getCoordinate <em>Coordinate</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Dependency#getLocal <em>Local</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDependency()
 * @model
 * @generated
 */
public interface Dependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Coordinate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coordinate</em>' attribute.
   * @see #setCoordinate(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDependency_Coordinate()
   * @model
   * @generated
   */
  String getCoordinate();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Dependency#getCoordinate <em>Coordinate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coordinate</em>' attribute.
   * @see #getCoordinate()
   * @generated
   */
  void setCoordinate(String value);

  /**
   * Returns the value of the '<em><b>Local</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local</em>' attribute.
   * @see #setLocal(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getDependency_Local()
   * @model
   * @generated
   */
  String getLocal();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Dependency#getLocal <em>Local</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local</em>' attribute.
   * @see #getLocal()
   * @generated
   */
  void setLocal(String value);

} // Dependency
