/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSON</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getJSON()
 * @model
 * @generated
 */
public interface JSON extends EObject
{
} // JSON
