/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Projection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Projection#getEvents <em>Events</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getProjection()
 * @model
 * @generated
 */
public interface Projection extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Events</b></em>' reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getProjection_Events()
   * @model
   * @generated
   */
  EList<Event> getEvents();

} // Projection
