/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Meta Info</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getSlabel <em>Slabel</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getLabel <em>Label</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getTooltip <em>Tooltip</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getPrompt <em>Prompt</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getExamples <em>Examples</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getTypeMetaInfo()
 * @model
 * @generated
 */
public interface TypeMetaInfo extends EObject
{
  /**
   * Returns the value of the '<em><b>Slabel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slabel</em>' attribute.
   * @see #setSlabel(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getTypeMetaInfo_Slabel()
   * @model
   * @generated
   */
  String getSlabel();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getSlabel <em>Slabel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slabel</em>' attribute.
   * @see #getSlabel()
   * @generated
   */
  void setSlabel(String value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getTypeMetaInfo_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Tooltip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tooltip</em>' attribute.
   * @see #setTooltip(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getTypeMetaInfo_Tooltip()
   * @model
   * @generated
   */
  String getTooltip();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getTooltip <em>Tooltip</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tooltip</em>' attribute.
   * @see #getTooltip()
   * @generated
   */
  void setTooltip(String value);

  /**
   * Returns the value of the '<em><b>Prompt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prompt</em>' attribute.
   * @see #setPrompt(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getTypeMetaInfo_Prompt()
   * @model
   * @generated
   */
  String getPrompt();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.TypeMetaInfo#getPrompt <em>Prompt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prompt</em>' attribute.
   * @see #getPrompt()
   * @generated
   */
  void setPrompt(String value);

  /**
   * Returns the value of the '<em><b>Examples</b></em>' containment reference list.
   * The list contents are of type {@link org.fuin.dsl.cqrs.cqrsDsl.Literal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Examples</em>' containment reference list.
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getTypeMetaInfo_Examples()
   * @model containment="true"
   * @generated
   */
  EList<Literal> getExamples();

} // TypeMetaInfo
