/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getDoc <em>Doc</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getOptional <em>Optional</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getType <em>Type</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getGenerics <em>Generics</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getName <em>Name</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getOverridden <em>Overridden</em>}</li>
 * </ul>
 *
 * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends EObject
{
  /**
   * Returns the value of the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc</em>' attribute.
   * @see #setDoc(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getVariable_Doc()
   * @model
   * @generated
   */
  String getDoc();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getDoc <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc</em>' attribute.
   * @see #getDoc()
   * @generated
   */
  void setDoc(String value);

  /**
   * Returns the value of the '<em><b>Optional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Optional</em>' attribute.
   * @see #setOptional(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getVariable_Optional()
   * @model
   * @generated
   */
  String getOptional();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getOptional <em>Optional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Optional</em>' attribute.
   * @see #getOptional()
   * @generated
   */
  void setOptional(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Type)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getVariable_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Generics</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generics</em>' containment reference.
   * @see #setGenerics(GenericArgs)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getVariable_Generics()
   * @model containment="true"
   * @generated
   */
  GenericArgs getGenerics();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getGenerics <em>Generics</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generics</em>' containment reference.
   * @see #getGenerics()
   * @generated
   */
  void setGenerics(GenericArgs value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getVariable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Overridden</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Overridden</em>' containment reference.
   * @see #setOverridden(OverriddenTypeMetaInfo)
   * @see org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage#getVariable_Overridden()
   * @model containment="true"
   * @generated
   */
  OverriddenTypeMetaInfo getOverridden();

  /**
   * Sets the value of the '{@link org.fuin.dsl.cqrs.cqrsDsl.Variable#getOverridden <em>Overridden</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Overridden</em>' containment reference.
   * @see #getOverridden()
   * @generated
   */
  void setOverridden(OverriddenTypeMetaInfo value);

} // Variable
