/*
 * generated by Xtext 2.39.0
 */
package org.fuin.dsl.cqrs.validation;

import com.google.inject.Inject
import java.util.HashSet
import java.util.Iterator
import java.util.List
import java.util.Map
import java.util.Set
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.util.EcoreUtil
import org.eclipse.xtext.naming.IQualifiedNameProvider
import org.eclipse.xtext.resource.IContainer
import org.eclipse.xtext.resource.IEObjectDescription
import org.eclipse.xtext.resource.impl.ResourceDescriptionsProvider
import org.eclipse.xtext.validation.Check
import org.fuin.dsl.cqrs.cqrsDsl.AbstractElement
import org.fuin.dsl.cqrs.cqrsDsl.Aggregate
import org.fuin.dsl.cqrs.cqrsDsl.AggregateId
import org.fuin.dsl.cqrs.cqrsDsl.Attribute
import org.fuin.dsl.cqrs.cqrsDsl.Consistency
import org.fuin.dsl.cqrs.cqrsDsl.ConsistencyLevel
import org.fuin.dsl.cqrs.cqrsDsl.Constraint
import org.fuin.dsl.cqrs.cqrsDsl.Context
import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage
import org.fuin.dsl.cqrs.cqrsDsl.Dependency
import org.fuin.dsl.cqrs.cqrsDsl.Entity
import org.fuin.dsl.cqrs.cqrsDsl.EntityId
import org.fuin.dsl.cqrs.cqrsDsl.Event
import org.fuin.dsl.cqrs.cqrsDsl.Exception
import org.fuin.dsl.cqrs.cqrsDsl.ExternalType
import org.fuin.dsl.cqrs.cqrsDsl.InternalType
import org.fuin.dsl.cqrs.cqrsDsl.Method
import org.fuin.dsl.cqrs.cqrsDsl.Parameter
import org.fuin.dsl.cqrs.cqrsDsl.Import
import org.fuin.dsl.cqrs.cqrsDsl.Module
import org.fuin.dsl.cqrs.cqrsDsl.ReturnType
import org.fuin.dsl.cqrs.cqrsDsl.Service
import org.fuin.dsl.cqrs.cqrsDsl.ValueObject
import org.fuin.dsl.cqrs.cqrsDsl.Variable
import org.fuin.dsl.cqrs.analysis.CqrsModuleDependencies
import org.fuin.dsl.cqrs.scoping.CqrsDependencies
import org.fuin.dsl.cqrs.scoping.CqrsModelArchives
import org.fuin.dsl.cqrs.scoping.RemoteScopeEntry

import org.eclipse.emf.common.util.EList
import org.fuin.dsl.cqrs.cqrsDsl.Type
import static extension org.fuin.dsl.cqrs.extensions.CqrsAbstractElementExtensions.*
import static extension org.fuin.dsl.cqrs.extensions.CqrsAggregateExtensions.*
import static extension org.fuin.dsl.cqrs.extensions.CqrsAttributeExtensions.*
import static extension org.fuin.dsl.cqrs.extensions.CqrsCollectionExtensions.*
import static extension org.fuin.dsl.cqrs.extensions.CqrsConstraintExtension.*
import static extension org.fuin.dsl.cqrs.extensions.CqrsEntityExtensions.*
import static extension org.fuin.dsl.cqrs.extensions.CqrsEObjectExtensions.*
import static extension org.fuin.dsl.cqrs.extensions.CqrsParameterExtensions.*
import org.eclipse.xtext.EcoreUtil2
import org.fuin.dsl.cqrs.cqrsDsl.BusinessRule
import org.fuin.dsl.cqrs.cqrsDsl.BusinessRuleInstance
import org.fuin.dsl.cqrs.cqrsDsl.Command
import org.fuin.dsl.cqrs.cqrsDsl.Constructor
import org.fuin.dsl.cqrs.cqrsDsl.IdentityArgument
import org.fuin.dsl.cqrs.cqrsDsl.Hint
import org.fuin.dsl.cqrs.cqrsDsl.View
import org.fuin.dsl.cqrs.cqrsDsl.ProcessManager
import org.fuin.dsl.cqrs.cqrsDsl.ProcessState
import org.fuin.dsl.cqrs.cqrsDsl.ProcessReaction
import org.fuin.dsl.cqrs.cqrsDsl.AnnotationInstance
import java.util.Collections
import java.util.ArrayList

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CqrsDslValidator extends AbstractCqrsDslValidator {
	
	static val MSG_DIRECT_REF_AGGREGATE = "A direct reference to an aggregate is only allowed from entities in the same aggregate"

	static val MSG_DIRECT_REF_ENTITY = "A direct reference to an entity is only allowed from entities in the same aggregate"

	public static val INVALID_VAR_NAME = 'invalidVarName'

	public static val EVENT_ONLY_ALLOWED_FOR_ENTITY = 'eventOnlyAllowedForEntity'

	public static val CONSTRAINT_MSG_UNKNOWN_VAR = 'constraintMsgUnknownVar'

	public static val EXCEPTION_MSG_UNKNOWN_VAR = 'exceptionMsgUnknownVar'

	public static val PROCESS_STATE_DUPLICATE = 'processStateDuplicate'

	public static val PROCESS_CORRELATION_KEY_UNKNOWN = 'processCorrelationKeyUnknown'

	public static val REF_TO_AGGREGATE_NOT_ALLOWED = 'refToAggregateNotAllowed'

	public static val REF_TO_ENTITY_NOT_ALLOWED = 'refToEntityNotAllowed'

	public static val MISSING_DOC = 'missingDOC'

	public static val EVENT_MSG_UNKNOWN_VAR = 'eventMsgUnknownVar'

	public static val COMMAND_MSG_UNKNOWN_VAR = 'commandMsgUnknownVar'

	public static val COMMAND_MSG_NOT_A_PATH = 'commandMsgNotAPath'

	public static val COMMAND_MSG_UNCLOSED_VAR = 'commandMsgUnclosedVar'

	public static val RULE_OWN_ID_IN_CONSTRUCTOR = 'ruleOwnIdInConstructor'

	public static val RULE_EXCEPTION_NOT_SUPPLIED = 'ruleExceptionNotSupplied'

	public static val RULE_ACTUALS_MISMATCH = 'ruleActualsMismatch'

	public static val EXCEPTION_DUPLICATE_CID = 'exceptionDuplicateCID'

	public static val DEPENDENCY_INVALID_COORDINATE = 'dependencyInvalidCoordinate'

	public static val DEPENDENCY_DUPLICATE = 'dependencyDuplicate'

	public static val DEPENDENCY_UNRESOLVED = 'dependencyUnresolved'

	public static val IMPORT_UNRESOLVED = 'importUnresolved'

	public static val IMPORT_DUPLICATE = 'importDuplicate'

	public static val IMPORT_UNUSED = 'importUnused'

	public static val MODULE_DEPENDENCY_CYCLE = 'moduleDependencyCycle'

	public static val SERVICE_METHOD_CANNOT_FIRE_EVENTS = "serviceMethodCannotFireEvents"

	public static val SERVICE_METHOD_CANNOT_DECLARE_EVENTS = "serviceMethodCannotDeclareEvents"

	public static val REST_PATH_ONLY_ON_VIEW_METHODS = "restPathOnlyOnViewMethods"

	public static val REST_PATH_UNKNOWN_VAR = "restPathUnknownVar"

	public static val BUSINESS_RULE_REQUIRES_EXCEPTION = "businessRuleRequiresException"

	public static val BUSINESS_RULE_REQUIRES_CONSISTENCY = "businessRuleRequiresConsistency"

	public static val ATTRIBUTE_INVARIANT_WRONG_TARGET_TYPE = "attributeInvariantWrongTargetType"

	public static val PARAMETER_CONSTRAINT_WRONG_TARGET_TYPE = "parameterConstraintWrongTargetType"

	public static val INTERNAL_TYPE_INVARIANT_WRONG_TARGET_TYPE = "internalTypeInvariantWrongTargetType"

	public static val WEAK_CONSISTENCY_REQUIRES_DETAILS = "weakConsistencyRequiresDetails"

	public static val STRONG_CONSISTENCY_DOES_NOT_ALLOW_DETAILS = "strongConsistencyDoesNotAllowDetails"

	public static val WRONG_IDENTIFIES_AGGREGATE = "wrongIdentifiesAggregate"

	public static val IDENTIFIES_AGGREGATE_NULL = "identifiesAggregateNull"

	public static val WRONG_IDENTIFIES_ENTITY = "wrongIdentifiesEntity"

	public static val IDENTIFIES_ENTITY_NULL = "identifiesEntityNull"

	public static val WRONG_ROOT_AGGREGATE = "wrongRootAggregate"

	public static val ROOT_NULL = "rootNull"

	public static val AGGREGATE_WITHOUT_ID = "aggregateWithoutId"

	public static val AGGREGATE_WITH_DUPLICATE_ID = "aggregateWithDuplicateId"

	public static val ENTITY_WITHOUT_ID = "entityWithoutId"

	public static val ENTITY_WITH_DUPLICATE_ID = "entityWithDuplicateId"

	public static val ILLEGAL_AGGREGATE_ELEMENT = "illegalAggregateElement"

	public static val ILLEGAL_ENTITY_ELEMENT = "illegalEntityElement"

	public static val MULTIPLE_AGGREGATE_ID_ELEMENTS = "multipleAggregateIdElements"

	public static val MULTIPLE_ENTITY_ID_ELEMENTS = "multipleEntityIdElements"

	public static val VAR_GENERICS_COUNT_MISMATCH = "varGenericsCountMismatch"

	public static val RETURN_TYPE_GENERICS_COUNT_MISMATCH = "returnTypeGenericsCountMismatch"

	public static val ANNOTATION_PARAM_COUNT_MISMATCH = "annotationParamCountMismatch"

	public static val VALUE_OBJECT_BASE_NO_CONSTRUCTORS_OR_METHODS = "valueObjectBaseNoConstructorsOrMethods"

	public static val INVALID_CRON_EXPRESSION = "invalidCronExpression"

	public static val HINT_JSON_SCHEMA_VIOLATION = "hintJsonSchemaViolation"

	public static val JPA_HINT_OUTSIDE_VIEW = "jpaHintOutsideView"

	@Inject
	IContainer.Manager containerManager

	@Inject
	ResourceDescriptionsProvider resourceDescriptionsProvider;

	@Inject
	IQualifiedNameProvider qualifiedNameProvider;

	@Inject
	CqrsDependencies dependencies;

	@Check
	def checkNameStartsWithCapital(Variable variable) {
		if (!Character::isLowerCase(variable.name.charAt(0))) {
			warning("Variable names should start with a lower case", variable,
				CqrsDslPackage.Literals::VARIABLE__NAME, INVALID_VAR_NAME)
		}
	}

	/** A dependency coordinate must be a Maven GAV: "groupId:artifactId:version". */
	@Check
	def checkDependencyCoordinate(Dependency dependency) {
		if (RemoteScopeEntry.parse(dependency.coordinate, dependency.local) === null) {
			error(
				"A dependency must be 'groupId:artifactId:version', but was '" + dependency.coordinate + "'",
				dependency,
				CqrsDslPackage.Literals::DEPENDENCY__COORDINATE,
				DEPENDENCY_INVALID_COORDINATE
			)
		}
	}

	/**
	 * A well formed coordinate must also resolve to something. Without this the only symptom of a
	 * missing artifact is every type it provides failing to resolve, which points at the models
	 * instead of at the declaration that is actually wrong.
	 */
	@Check
	def checkDependencyResolves(Dependency dependency) {
		val problem = dependencies.resolutionProblem(dependency)
		if (problem !== null) {
			error(
				"Cannot resolve dependency '" + dependency.coordinate + "': " + problem,
				dependency,
				CqrsDslPackage.Literals::DEPENDENCY__COORDINATE,
				DEPENDENCY_UNRESOLVED
			)
		}
	}

	/**
	 * The same artifact must not be declared twice in one block, nor repeated on a module that
	 * already inherits it from its context.
	 */
	@Check
	def checkDuplicateDependency(Dependency dependency) {
		val coordinate = dependency.coordinate
		if(coordinate === null) return;
		val container = dependency.eContainer

		val siblings = switch container {
			Context: container.dependencies
			Module: container.dependencies
			default: null
		}
		if(siblings === null) return;
		if (siblings.filter[it.coordinate == coordinate].size > 1 && siblings.findFirst [
			it.coordinate == coordinate
		] !== dependency) {
			error("Duplicate dependency '" + coordinate + "'", dependency,
				CqrsDslPackage.Literals::DEPENDENCY__COORDINATE, DEPENDENCY_DUPLICATE)
			return;
		}

		if (container instanceof Module) {
			val context = container.eContainer
			if (context instanceof Context) {
				if (context.dependencies.exists[it.coordinate == coordinate]) {
					warning(
						"Dependency '" + coordinate + "' is already declared by context '" + context.name + "'",
						dependency, CqrsDslPackage.Literals::DEPENDENCY__COORDINATE, DEPENDENCY_DUPLICATE)
				}
			}
		}
	}

	/**
	 * An import must address something that exists: a context, a module or a single type. Anything
	 * else is a typo that would silently leave every name it was meant to provide unresolved.
	 */
	@Check
	def checkImportResolves(Import imp) {
		val imported = imp.importedNamespace
		if(imported.nullOrEmpty) return;

		if (!importMatchesAnything(imp, imported)) {
			error("Import '" + imported + "' does not match any context, module or type", imp,
				CqrsDslPackage.Literals::IMPORT__IMPORTED_NAMESPACE, IMPORT_UNRESOLVED)
		}
	}

	/**
	 * The same name must not be imported twice in one block, nor repeated on a module that already
	 * inherits it from its context.
	 */
	@Check
	def checkDuplicateImport(Import imp) {
		val imported = imp.importedNamespace
		if(imported.nullOrEmpty) return;
		val container = imp.eContainer

		val siblings = switch container {
			Context: container.imports
			Module: container.imports
			default: null
		}
		if(siblings === null) return;
		if (siblings.filter[it.importedNamespace == imported].size > 1 &&
			siblings.findFirst[it.importedNamespace == imported] !== imp) {
			error("Duplicate import '" + imported + "'", imp,
				CqrsDslPackage.Literals::IMPORT__IMPORTED_NAMESPACE, IMPORT_DUPLICATE)
			return;
		}

		if (container instanceof Module) {
			val context = container.eContainer
			if (context instanceof Context) {
				if (context.imports.exists[it.importedNamespace == imported]) {
					warning(
						"Import '" + imported + "' is already declared by context '" + context.name + "'",
						imp, CqrsDslPackage.Literals::IMPORT__IMPORTED_NAMESPACE, IMPORT_DUPLICATE)
				}
			}
		}
	}

	/** An import nothing in the block refers to is dead weight and hides the real coupling. */
	@Check
	def checkUnusedImport(Import imp) {
		val imported = imp.importedNamespace
		if(imported.nullOrEmpty) return;
		val container = imp.eContainer
		if(container === null) return;

		// An unresolvable import is reported by checkImportResolves - do not pile a second marker on it.
		if(!importMatchesAnything(imp, imported)) return;

		if(referencedNames(container).exists[covers(imported, it)]) return;

		// Nothing here refers to it - as far as could be seen. A name that did not resolve belongs to
		// no import in particular, and it may well be the one this import was written for, so there is
		// no honest way to call the import dead weight while it is around.
		if(hasUnresolvedReference(container)) return;

		warning("Import '" + imported + "' is not used", imp,
			CqrsDslPackage.Literals::IMPORT__IMPORTED_NAMESPACE, IMPORT_UNUSED)
	}

	/**
	 * Reports a module that takes part in a dependency cycle.
	 *
	 * <p>A cycle means neither module can be reasoned about - or switched off - without the other, and
	 * the generated module dependency graph would have no topological order to offer a consumer. It is
	 * an error rather than a warning because there is no version of it that is intended.</p>
	 *
	 * <p><b>A module, not a bounded context.</b> The nodes are the {@code module} blocks as declared,
	 * so a view or a process manager is a node of its own. That granularity is what keeps the seams
	 * between contexts legal: a process manager may react to another context's events while the
	 * context it lives beside stays independent of it. Rolling the sub-modules up into their context
	 * is a question a consumer of the generated graph can ask; it is not what this rule enforces.</p>
	 *
	 * <p><b>The build is the enforcement point.</b> SrcGen4J parses the whole model into one resource
	 * set, so a build sees every module and every edge. An editor validates one resource and reaches
	 * the rest only through the index, so a cycle closed by a file that is not open may surface late
	 * or not at all. That is a deliberate trade: no editor-side index walk on every keystroke, and the
	 * build refuses regardless.</p>
	 */
	@Check
	def checkModuleDependencyCycle(Module module) {
		if(CqrsModelArchives.isArchived(module.eResource?.URI)) return;

		val graph = CqrsModuleDependencies.graphOf(module.eResource?.resourceSet)
		val cycle = CqrsModuleDependencies.cycleThrough(module.name, graph)
		if(cycle.empty) return;

		error("Module '" + module.name + "' is part of a dependency cycle: " + cycle.join(" -> "),
			module, CqrsDslPackage.Literals::MODULE__NAME, MODULE_DEPENDENCY_CYCLE)
	}

	/**
	 * Whether anything inside the given block points at something that could not be resolved. Only
	 * asked when an import is about to be reported as unused, which is rare enough for a second walk.
	 */
	private def boolean hasUnresolvedReference(EObject container) {
		val contents = container.eAllContents
		while (contents.hasNext) {
			val EObject obj = contents.next
			for (reference : obj.eClass.EAllReferences.filter[!containment && !derived]) {
				val value = obj.eGet(reference, false)
				val targets = if (reference.many) value as List<?> else Collections.singletonList(value)
				for (target : targets.filterNull) {
					if (target instanceof EObject) {
						if(target.eIsProxy) return true
					}
				}
			}
		}
		return false
	}

	/**
	 * The qualified names of everything the cross references inside the given block resolve to. A
	 * context is asked for its own references and for those of all of its modules, because a context
	 * level import serves them all.
	 *
	 * <p>The references are <em>resolved</em> rather than read as they lie. Xtext links lazily: until
	 * somebody asks for the target, the feature still holds a proxy, and a proxy would be read here as
	 * "this name refers to nothing" - which turns into "the import providing it is unused". Whether the
	 * editor happened to have resolved a name already, because a hover or a Ctrl-click asked for it,
	 * must not decide whether its import is reported.</p>
	 */
	private def Iterable<String> referencedNames(EObject container) {
		// Delegated so this and the module dependency graph can never disagree about what a block
		// refers to - one walk, two questions asked of its answer.
		return CqrsModuleDependencies.referencedNames(container, qualifiedNameProvider)
	}

	/**
	 * Whether an imported name covers a fully qualified name: an exact match, or - for a wildcard -
	 * a name below its prefix.
	 */
	private def boolean covers(String imported, String qualifiedName) {
		if (imported.endsWith(".*")) {
			return qualifiedName.startsWith(imported.substring(0, imported.length - 1))
		}
		return imported == qualifiedName
	}

	/**
	 * Whether anything the resource can address matches the imported name: what the index holds, and
	 * what the declared dependencies provide.
	 *
	 * <p>The second half is not a shortcut for the first. In an IDE the index is the workspace
	 * builder state, which knows the project's files and never a model read out of a dependency's
	 * zip - while the scope such an import feeds does see them, through
	 * {@link CqrsDslGlobalScopeProvider}. Asking both is what keeps this check from reporting an
	 * import whose types resolve perfectly well. Headless the two overlap, because there the index
	 * <em>is</em> the resource set the dependency models are loaded into.</p>
	 */
	private def boolean importMatchesAnything(Import imp, String imported) {
		val resource = imp.eResource
		if(resource === null) return true;
		val resourceDescriptions = resourceDescriptionsProvider.getResourceDescriptions(resource)
		val resourceDescription = resourceDescriptions.getResourceDescription(resource.URI)
		if(resourceDescription === null) return true;

		for (container : containerManager.getVisibleContainers(resourceDescription, resourceDescriptions)) {
			for (IEObjectDescription descr : container.getExportedObjects()) {
				val name = descr.name
				if (name !== null && covers(imported, name.toString)) {
					return true
				}
			}
		}
		return dependencies.providedNames(resource).exists[covers(imported, it.toString)]
	}

	/**
	 * A model read out of a dependency's archive is not reported on. It is opened read-only, it
	 * belongs to another project, and whoever authored it has validated it there - a marker on it
	 * would name a problem the reader cannot fix. This mirrors what the IntelliJ plugin does for a
	 * file outside the project.
	 */
	override protected boolean isResponsible(Map<Object, Object> context, EObject eObject) {
		if(!super.isResponsible(context, eObject)) return false
		return !CqrsModelArchives.isArchived(eObject.eResource?.URI)
	}

	@Check
	def checkVariablesInConstraintMessage(Constraint constraint) {
		val name = findUnknownVar(constraint.allAllowedVariables.asNames, constraint.message);
		if (name !== null) {
			error(
				"A variable with the name '" + name + "' is unknown",
				constraint,
				CqrsDslPackage.Literals::CONSTRAINT__MESSAGE,
				CONSTRAINT_MSG_UNKNOWN_VAR
			)
		}
	}

	@Check
	def checkVariablesInExceptionMessage(Exception ex) {
		val name = findUnknownVar(ex.attributes.asNames, ex.message);
		if (name !== null) {
			error(
				"A variable '" + name + "' is not defined in the exception",
				ex,
				CqrsDslPackage.Literals::EXCEPTION__MESSAGE,
				EXCEPTION_MSG_UNKNOWN_VAR
			)
		}
	}

	@Check
	def checkForbiddenTypeRefs(Variable variable) {

		if (variable.type instanceof Aggregate) {
			val Aggregate aggregate = (variable.type as Aggregate);
			val Entity parentEntity = getParent(Entity, variable)
			if ((parentEntity === null) || !aggregate.same(parentEntity.root)) {
				error(
					MSG_DIRECT_REF_AGGREGATE,
					variable,
					CqrsDslPackage.Literals::VARIABLE__TYPE,
					REF_TO_AGGREGATE_NOT_ALLOWED,
					aggregate.idTypeNullsafe.name
				)
			}
		}

		if (variable.type instanceof Entity) {
			val Entity entity = (variable.type as Entity);
			val Aggregate aggregateOfVariable = getAggregate(variable)
			if ((aggregateOfVariable === null) || !aggregateOfVariable.same(entity.root)) {
				error(
					MSG_DIRECT_REF_ENTITY,
					variable,
					CqrsDslPackage.Literals::VARIABLE__TYPE,
					REF_TO_ENTITY_NOT_ALLOWED,
					entity.idTypeNullsafe.name
				)
			}
		}

	}

	@Check
	def checkNoRefToAggregate(Method method) {

		if (method.returnType.type instanceof Aggregate) {

			val Aggregate aggregate = (method.returnType.type as Aggregate);
			val Entity parentEntity = getParent(Entity, method)
			if ((parentEntity === null) || !aggregate.same(parentEntity.root)) {
				error(
					MSG_DIRECT_REF_AGGREGATE,
					method,
					CqrsDslPackage.Literals::METHOD__RETURN_TYPE,
					REF_TO_AGGREGATE_NOT_ALLOWED,
					aggregate.idTypeNullsafe.name
				)
			}

		} else if (method.returnType.type instanceof Entity) {

			val Entity entity = (method.returnType.type as Entity);
			val Entity parentEntity = getParent(Entity, method)
			if ((parentEntity === null) || !entity.root.same(parentEntity.root)) {
				error(
					MSG_DIRECT_REF_ENTITY,
					method,
					CqrsDslPackage.Literals::METHOD__RETURN_TYPE,
					REF_TO_ENTITY_NOT_ALLOWED,
					entity.idTypeNullsafe.name
				)
			}

		}

	}

	@Check
	def checkNoEventsInService(Method method) {

		if (method.eContainer instanceof Service) {

			// No fired events
			if ((method.firedEvents !== null) && (method.firedEvents.size() > 0)) {
				error(
					"A service method cannot fire events",
					method,
					CqrsDslPackage.Literals::ABSTRACT_METHOD__FIRED_EVENTS,
					SERVICE_METHOD_CANNOT_FIRE_EVENTS
				)
			}

			// No declared events
			if ((method.events !== null) && (method.events.size() > 0)) {
				error(
					"A service method cannot declare events",
					method,
					CqrsDslPackage.Literals::ABSTRACT_METHOD__EVENTS,
					SERVICE_METHOD_CANNOT_DECLARE_EVENTS
				)
			}

		}

	}

	@Check
	def checkMethodRestPath(Method method) {

		if (method.restPath === null) {
			return
		}

		// Only views are exposed as HTTP endpoints, so a REST path is meaningless anywhere else
		if (!(method.eContainer instanceof View)) {
			error(
				"A 'rest-path' is only allowed for a view method",
				method,
				CqrsDslPackage.Literals::METHOD__REST_PATH,
				REST_PATH_ONLY_ON_VIEW_METHODS
			)
			return
		}

		// Every "{name}" placeholder becomes a path variable bound to a parameter of that name
		val names = method.parameters.asNames
		val name = findUnknownPathVar(names, method.restPath);
		if (name !== null) {
			error(
				"A parameter with the name '" + name + "' is unknown",
				method,
				CqrsDslPackage.Literals::METHOD__REST_PATH,
				REST_PATH_UNKNOWN_VAR
			)
		}

	}

	@Check
	def checkVariablesInEventMessage(Event event) {
		if (event.message !== null) {
			val List<String> vars = new ArrayList<String>(event.attributes.asNames)
			// Attributes copied from a constructor/method via 'copies-attributes-of' are also valid
			if (event.origin !== null) {
				vars.addAll(event.origin.parameters.asNames)
			}
			val name = findUnknownVar(vars, event.message);
			if (name !== null) {
				error(
					"A variable with the name '" + name + "' is unknown",
					event,
					CqrsDslPackage.Literals::EVENT__MESSAGE,
					EVENT_MSG_UNKNOWN_VAR
				)
			}
		}
	}

	/**
	 * Checks that every variable in a command's message is one the command carries.
	 *
	 * <p>Deliberately stricter than the event check above. An event's message is rendered by the JVM
	 * alone, so anything Jakarta EL understands is fair game. A command's message is a confirmation
	 * prompt shown <em>before</em> the command is sent, so the client renders it too - and a Dart
	 * client has no EL engine. What a command may write is therefore the intersection: a plain
	 * identifier or a dotted path, checked here so the two renderers cannot drift.
	 */
	@Check
	def checkVariablesInCommandMessage(Command command) {
		if (command.message !== null) {
			// The generated command carries the target operation's parameters as well as its own
			// attributes - most commands declare none and take all of theirs from the target.
			val List<String> vars = new ArrayList<String>()
			if (command.target !== null) {
				vars.addAll(command.target.parameters.asNames)
			}
			vars.addAll(command.attributes.asNames)
			val problem = findUnusableCommandVar(vars, command.message)
			if (problem !== null) {
				error(
					problem.value,
					command,
					CqrsDslPackage.Literals::COMMAND__MESSAGE,
					problem.key
				)
			}
		}
	}

	/**
	 * Checks that a creating operation does not hand a rule the carrier's own identity.
	 *
	 * <p>'own-id' reads the identity off the instance the operation is called on, and a constructor has
	 * none - it is what brings the instance into being. The generated validator's method for a creating
	 * operation is static for exactly that reason, so there would be nothing to read it from.
	 */
	/**
	 * Checks that a rule holds everything its refusal needs to name.
	 *
	 * <p>An exception declares what it needs in order to say what it refused; a rule declares what it
	 * decides from. The two overlap by name, which is why a rule commonly carries an attribute that
	 * plays no part in its condition. Where they do not overlap the generated rule cannot construct its
	 * own refusal - and without this that surfaces as a generator failure at the far end of a release
	 * chain, or as generated Java missing an argument.
	 *
	 * <p>Only where a condition is declared, because that is what decides whether a class is generated
	 * at all. A rule without one is written by hand and constructs its refusal however it likes; a rule
	 * that has not yet been given its inputs is not yet wrong, it is not yet finished.
	 */
	@Check
	def checkRuleSuppliesItsException(BusinessRule rule) {
		if (rule.exception === null || rule.requires === null) {
			return
		}
		val declared = rule.attributes.asNames
		for (attribute : rule.exception.attributes) {
			if (!declared.contains(attribute.name)) {
				error(
					rule.exception.name + " needs '" + attribute.name + "' to say what it refused, and "
						+ rule.name + " does not declare it",
					rule,
					CqrsDslPackage.Literals::BUSINESS_RULE__EXCEPTION,
					RULE_EXCEPTION_NOT_SUPPLIED
				)
				return
			}
		}
	}

	/**
	 * Checks that a rule usage hands over as many values as the rule declares.
	 *
	 * <p>The actuals bind positionally, so one too few or one too many silently shifts every value
	 * after it - and because everything here is a reference rather than a literal, the result usually
	 * still type-checks.
	 */
	@Check
	def checkRuleActuals(BusinessRuleInstance instance) {
		val rule = instance.businessRule
		if (rule === null || rule.eIsProxy) {
			return
		}
		val expected = rule.attributes.nullSafe.size
		val actual = instance.params.nullSafe.size
		if (expected !== actual) {
			error(
				rule.name + " decides from " + expected + " value(s), but " + actual + " were given",
				instance,
				CqrsDslPackage.Literals::BUSINESS_RULE_INSTANCE__BUSINESS_RULE,
				RULE_ACTUALS_MISMATCH
			)
		}
	}

	@Check
	def checkOwnIdOutsideConstructor(IdentityArgument argument) {
		val constructor = EcoreUtil2.getContainerOfType(argument, Constructor)
		if (constructor !== null) {
			error(
				"'own-id' has nothing to read in a constructor, which is what creates the identity",
				argument,
				null,
				RULE_OWN_ID_IN_CONSTRUCTOR
			)
		}
	}

	@Check
	def checkViewCronSchedule(View view) {
		if (view.cron !== null && !SpringCronExpression.isValid(view.cron)) {
			error(
				"Invalid Spring cron expression: '" + view.cron + "'",
				view,
				CqrsDslPackage.Literals::VIEW__CRON,
				INVALID_CRON_EXPRESSION
			)
		}
	}

	@Check
	def checkProcessManagerCronSchedule(ProcessManager pm) {
		if (pm.cron !== null && !SpringCronExpression.isValid(pm.cron)) {
			error(
				"Invalid Spring cron expression: '" + pm.cron + "'",
				pm,
				CqrsDslPackage.Literals::PROCESS_MANAGER__CRON,
				INVALID_CRON_EXPRESSION
			)
		}
	}

	@Check
	def checkHintJsonSchema(Hint hint) {
		// (a) Validate the JSON of a known hint (e.g. "JpaHint" / "SrcGen4J") against its JSON schema.
		val schema = CqrsHintJson.schemaForHintName(hint.name)
		if (schema !== null && hint.json !== null) {
			for (String msg : CqrsHintJson.validate(hint.json, schema)) {
				error(msg, hint, CqrsDslPackage.Literals::HINT__JSON, HINT_JSON_SCHEMA_VIOLATION)
			}
		}
		// (b) A "JpaHint" only generates code when it is declared inside a view.
		if ("JpaHint" == simpleHintName(hint.name) && !(hint.eContainer instanceof View)) {
			warning(
				"JpaHint only generates code inside a view",
				hint,
				CqrsDslPackage.Literals::HINT__NAME,
				JPA_HINT_OUTSIDE_VIEW
			)
		}
	}

	private def String simpleHintName(String name) {
		if (name === null) {
			return null
		}
		val p = name.lastIndexOf('.')
		if (p < 0) name else name.substring(p + 1)
	}

	@Check
	def checkUniqueProcessStateNames(ProcessManager pm) {
		val Set<String> seen = new HashSet<String>()
		for (ProcessState state : pm.states) {
			if (!seen.add(state.name)) {
				error(
					"Duplicate process state '" + state.name + "'",
					state,
					CqrsDslPackage.Literals::PROCESS_STATE__NAME,
					PROCESS_STATE_DUPLICATE
				)
			}
		}
	}

	@Check
	def checkCorrelateByAttribute(ProcessReaction reaction) {
		val String key = reaction.correlationKey
		val Event event = reaction.event
		if (key !== null && event !== null && !event.eIsProxy) {
			val List<String> vars = new ArrayList<String>(event.attributes.asNames)
			// Attributes copied from a constructor/method via 'copies-attributes-of' are also valid
			if (event.origin !== null) {
				vars.addAll(event.origin.parameters.asNames)
			}
			if (!vars.contains(key)) {
				error(
					"The correlation key '" + key + "' is not an attribute of event '" + event.name + "'",
					reaction,
					CqrsDslPackage.Literals::PROCESS_REACTION__CORRELATION_KEY,
					PROCESS_CORRELATION_KEY_UNKNOWN
				)
			}
		}
	}

	@Check
	def checkUniqueExceptionUID(Exception ex) {

		var String name = null
		var int max = 0
		val Iterator<Exception> allExceptions = getAllExceptions(ex).iterator
		while (allExceptions.hasNext) {
			val Exception other = allExceptions.next

			// Find highest number
			if ((other.cid > max) && ex.context.name.equals(other.context.name)) {
				max = other.cid
			}

			// Check for duplicate
			if ((name === null) && (ex != other) && (ex.cid > 0) && (ex.cid == other.cid) &&
				ex.context.name.equals(other.context.name)) {
				name = other.name
			}
		}

		if (name !== null) {
			val String nextId = "" + (max + 1)
			error(
				"The CID is already used by exception '" + name + "'",
				ex,
				CqrsDslPackage.Literals::EXCEPTION__CID,
				EXCEPTION_DUPLICATE_CID,
				nextId
			)
		}
	}

	@Check
	def checkAttributeInvariantsTargetType(Attribute attribute) {

		if ((attribute.invariants !== null) && (attribute.invariants.constraintInstances !== null)) {
			for (constraintInstance : attribute.invariants.constraintInstances) {
				if (constraintInstance.constraint.input !== null && constraintInstance.constraint.input.length() > 0 
					&& !constraintInstance.constraint.input.contains(attribute.type)
				) {
					error(
						"The allowed input types of the constraint (" + constraintInstance.constraint.input.typeNames +
							") do not match the attribute type",
						constraintInstance,
						CqrsDslPackage.Literals::CONSTRAINT_INSTANCE__CONSTRAINT,
						ATTRIBUTE_INVARIANT_WRONG_TARGET_TYPE
					)
				}
			}
		}

	}

	@Check
	def checkParameterConstraintsTargetType(Parameter parameter) {

		if ((parameter.preconditions !== null) && (parameter.preconditions.constraintInstances !== null)) {
			for (constraintInstance : parameter.preconditions.constraintInstances) {
				if (!constraintInstance.constraint.input.contains(parameter.type)) {
					error(
						"The input type of the constraint (" + constraintInstance.constraint.input.typeNames +
							") does not match the parameter type",
						constraintInstance,
						CqrsDslPackage.Literals::CONSTRAINT_INSTANCE__CONSTRAINT,
						PARAMETER_CONSTRAINT_WRONG_TARGET_TYPE
					)
				}
			}
		}

	}

	@Check
	def checkInternalTypeInvariantsTargetType(InternalType internalType) {

		if ((internalType.invariants !== null) && (internalType.invariants.constraintInstances !== null)) {

			for (constraintInstance : internalType.invariants.constraintInstances) {
				if (!constraintInstance.constraint.input.contains(internalType)) {
					error(
						"The input type of the constraint (" + constraintInstance.constraint.input.typeNames +
							") does not match this type",
						constraintInstance,
						CqrsDslPackage.Literals::CONSTRAINT_INSTANCE__CONSTRAINT,
						INTERNAL_TYPE_INVARIANT_WRONG_TARGET_TYPE
					)
				}
			}

		}

	}

	@Check
	def checkWeakConsistency(Consistency consistency) {

		if ((consistency.level == ConsistencyLevel.WEAK) && (consistency.weakConsistency === null)) {
			error(
				"You must define the details for weak consistency",
				consistency,
				CqrsDslPackage.Literals::CONSISTENCY__WEAK_CONSISTENCY,
				WEAK_CONSISTENCY_REQUIRES_DETAILS
			)
		}

		if ((consistency.level == ConsistencyLevel.STRONG) && (consistency.weakConsistency !== null)) {
			error(
				"No details required for strong consistency",
				consistency,
				CqrsDslPackage.Literals::CONSISTENCY__WEAK_CONSISTENCY,
				STRONG_CONSISTENCY_DOES_NOT_ALLOW_DETAILS
			)
		}

	}

	@Check
	def checkAggregateIdIdentifies(AggregateId aggregateId) {

		if (aggregateId.eContainer instanceof Aggregate) {
			if ((aggregateId.aggregate !== null) && (aggregateId.aggregate != aggregateId.eContainer)) {
				error(
					"An ID defined in an aggregate can only identify the parent aggregate",
					aggregateId,
					CqrsDslPackage.Literals::AGGREGATE_ID__AGGREGATE,
					WRONG_IDENTIFIES_AGGREGATE
				)
			}
		} else {
			if (aggregateId.aggregate === null) {
				error(
					"An ID defined outside an aggregate must use the 'identifies' expression",
					aggregateId,
					CqrsDslPackage.Literals::AGGREGATE_ID__AGGREGATE,
					IDENTIFIES_AGGREGATE_NULL
				)
			}
		}

	}

	@Check
	def checkEntityIdIdentifies(EntityId entityId) {

		if (entityId.eContainer instanceof Entity) {
			if ((entityId.entity !== null) && (entityId.entity != entityId.eContainer)) {
				error(
					"An ID defined in an entity can only identify the parent entity",
					entityId,
					CqrsDslPackage.Literals::ENTITY_ID__ENTITY,
					WRONG_IDENTIFIES_ENTITY
				)
			}
		} else {
			if (entityId.entity === null) {
				error(
					"An ID defined outside an entity must use the 'identifies' expression",
					entityId,
					CqrsDslPackage.Literals::ENTITY_ID__ENTITY,
					IDENTIFIES_ENTITY_NULL
				)
			}
		}

	}

	@Check
	def checkEntityRoot(Entity entity) {

		if (entity.eContainer instanceof Aggregate) {
			if ((entity.root !== null) && (entity.root != entity.eContainer)) {
				error(
					"An entity defined in an aggregate can only reference the parent aggregate",
					entity,
					CqrsDslPackage.Literals::ENTITY__ROOT,
					WRONG_ROOT_AGGREGATE
				)
			}
		} else {
			if (entity.root === null) {
				error(
					"An entity defined outside an aggregate must use the 'root' expression",
					entity,
					CqrsDslPackage.Literals::ENTITY__ROOT,
					ROOT_NULL
				)
			}
		}

	}

	@Check
	def checkEntityHasId(Entity entity) {

		if (entity.idType === null) {
			if (entity.entityId === null) {
				error(
					"Entity does not define an ID",
					entity,
					CqrsDslPackage.Literals::ENTITY__ID_TYPE,
					ENTITY_WITHOUT_ID
				)
			}
		} else {
			if (entity.entityId !== null) {
				error(
					"Entity cannot not reference an ID using 'identifier' and define another inside the aggregate",
					entity,
					CqrsDslPackage.Literals::ENTITY__ID_TYPE,
					ENTITY_WITH_DUPLICATE_ID
				)
			}
		}

	}

	@Check
	def checkAggregateHasId(Aggregate aggregate) {

		if (aggregate.idType === null) {
			if (aggregate.aggregateId === null) {
				error(
					"Aggregate does not define an ID",
					aggregate,
					CqrsDslPackage.Literals::AGGREGATE__ID_TYPE,
					AGGREGATE_WITHOUT_ID
				)
			}
		} else {
			if (aggregate.aggregateId !== null) {
				error(
					"Aggregate cannot not reference an ID using 'identifier' and define another inside the aggregate",
					aggregate,
					CqrsDslPackage.Literals::AGGREGATE__ID_TYPE,
					AGGREGATE_WITH_DUPLICATE_ID
				)
			}
		}

	}

	@Check
	def checkOnlyOneAggregateId(Aggregate aggregate) {

		if (aggregate.elements.nullSafe.filter(typeof(AggregateId)).size > 1) {
			error(
				"Only one 'aggregate-id' can be defined inside an aggregate",
				aggregate,
				CqrsDslPackage.Literals::ABSTRACT_ENTITY__ELEMENTS,
				MULTIPLE_AGGREGATE_ID_ELEMENTS
			)
		}

	}

	/**
	 * Restricts what an aggregate may hold as a nested element. Only the 'elements' list is meant: an
	 * aggregate's own 'business-rule' is an AbstractElement too - so that a shared rule can be a module
	 * element - but it lives in 'businessRules' and is not one of the nested elements this rule is about.
	 */
	@Check
	def checkAllowedAggregateElements(AbstractElement el) {

		if ((el.eContainer instanceof Aggregate) &&
			(el.eContainingFeature === CqrsDslPackage.Literals::ABSTRACT_ENTITY__ELEMENTS) &&
			!(el instanceof AggregateId || el instanceof Entity || el instanceof Event || el instanceof Command || el instanceof ValueObject )) {
			error(
				"Allowed elements in an aggregate are: 'aggregate-id', 'entity', 'event', 'command' and 'value-object'",
				el,
				CqrsDslPackage.Literals::ABSTRACT_ELEMENT__NAME,
				ILLEGAL_AGGREGATE_ELEMENT
			)
		}

	}

	@Check
	def checkOnlyOneEntityId(Entity entity) {

		if (entity.elements.nullSafe.filter(typeof(EntityId)).size > 1) {
			error(
				"Only one 'entity-id' can be defined inside an entity",
				entity,
				CqrsDslPackage.Literals::ABSTRACT_ENTITY__ELEMENTS,
				MULTIPLE_ENTITY_ID_ELEMENTS
			)
		}

	}

	/** The same for an entity: its own 'business-rule' is not one of its nested elements. */
	@Check
	def checkAllowedEntityElements(AbstractElement el) {

		if ((el.eContainer instanceof Entity) &&
			(el.eContainingFeature === CqrsDslPackage.Literals::ABSTRACT_ENTITY__ELEMENTS) &&
			!(el instanceof EntityId || el instanceof Event || el instanceof ValueObject )) {
			error(
				"Allowed elements in an entity are: 'entity-id', 'event' and 'value-object'",
				el,
				CqrsDslPackage.Literals::ABSTRACT_ELEMENT__NAME,
				ILLEGAL_ENTITY_ELEMENT
			)
		}

	}

	@Check
	def checkGenericArgs(Variable v) {
		
		if (v.type instanceof ExternalType) {
			val type = v.type as ExternalType
			if (v.generics === null) {
				if (type.generics > 0) {
					error(
						"The number of arguments does not match the number required by the type: " + type.generics,
						v,
						CqrsDslPackage.Literals::VARIABLE__GENERICS,
						VAR_GENERICS_COUNT_MISMATCH
					)
				}
			} else {
				if (v.generics.args.nullSafe.size != type.generics) {
					error(
						"The number of arguments does not match the number required by the type: " + type.generics,
						v,
						CqrsDslPackage.Literals::VARIABLE__GENERICS,
						VAR_GENERICS_COUNT_MISMATCH
					)
				}
			}
		}

	}

	@Check
	def checkReturnTypeGenericArgs(ReturnType rt) {

		if (rt.type instanceof ExternalType) {
			val type = rt.type as ExternalType
			if (rt.generics === null) {
				if (type.generics > 0) {
					error(
						"The number of arguments does not match the number required by the type: " + type.generics,
						rt,
						CqrsDslPackage.Literals::RETURN_TYPE__GENERICS,
						RETURN_TYPE_GENERICS_COUNT_MISMATCH
					)
				}
			} else {
				if (rt.generics.args.nullSafe.size != type.generics) {
					error(
						"The number of arguments does not match the number required by the type: " + type.generics,
						rt,
						CqrsDslPackage.Literals::RETURN_TYPE__GENERICS,
						RETURN_TYPE_GENERICS_COUNT_MISMATCH
					)
				}
			}
		}

	}

	@Check
	def checkAnnotationInstanceArgs(AnnotationInstance ai) {
		if (ai.annotation.attributes.nullSafe.size !== ai.params.nullSafe.size) {
			error(
				"The number of arguments does not match the number required by the type: " + ai.annotation.name,
				ai,
				CqrsDslPackage.Literals::ANNOTATION_INSTANCE__PARAMS,
				ANNOTATION_PARAM_COUNT_MISMATCH
			)
		}
	}
	
	@Check
	def checkValueObjectBaseHasNoConstructorsOrMethods(ValueObject vo) {
		if (vo.base !== null) {
			if (!vo.constructors.nullSafe.empty) {
				error(
					"A value object with a 'base' is not allowed to have constructors",
					vo,
					CqrsDslPackage.Literals::ABSTRACT_VO__CONSTRUCTORS,
					VALUE_OBJECT_BASE_NO_CONSTRUCTORS_OR_METHODS
				)
			}
			if (!vo.methods.nullSafe.empty) {
				error(
					"A value object with a 'base' is not allowed to have methods",
					vo,
					CqrsDslPackage.Literals::ABSTRACT_VO__METHODS,
					VALUE_OBJECT_BASE_NO_CONSTRUCTORS_OR_METHODS
				)
			}
		}
	}

	private def getAllExceptions(EObject obj) {
		val Set<Exception> list = new HashSet<Exception>()
		val resource = obj.eResource
		val resourceDescriptions = resourceDescriptionsProvider.getResourceDescriptions(resource)
		val resourceDescription = resourceDescriptions.getResourceDescription(resource.URI)
		val containers = containerManager.getVisibleContainers(resourceDescription, resourceDescriptions)
		for (container : containers) {
			for (IEObjectDescription descr : container.getExportedObjects()) {
				val EObject eObjectOrProxy = descr.getEObjectOrProxy()
				if (eObjectOrProxy instanceof Exception) {
					val Exception ex = EcoreUtil.resolve(eObjectOrProxy, obj) as Exception;
					list.add(ex)
				}
			}
		}
		return list
	}

	private static def String findUnknownVar(List<String> vars, String msg) {
		var int end = -1;
		var int from = 0;
		var int start = -1;
		while ((start = msg.indexOf("${", from)) > -1) {
			end = msg.indexOf('}', start + 1);
			if (end == -1) {

				// No closing bracket found...
				from = msg.length();
			} else {
				var String name = msg.substring(start + 2, end);
				// Only plain identifiers are checked. Complex Jakarta EL expressions (e.g.
				// "name.toUpperCase()", "quantity * price") are left to the EL engine. The implicit
				// "entityIdPath" variable is always available and therefore never flagged.
				if (isSimpleVariableName(name) && !vars.contains(name) && !name.equals("entityIdPath")) {
					return name
				}
				from = end + 1;
			}
		}
		return null
	}

	/**
	 * Returns the first "{name}" placeholder of a REST path that is not backed by one of the given
	 * parameter names, or NULL if all of them are known. Unlike a message variable a path variable
	 * has no "$" prefix and is always a plain identifier.
	 */
	private static def String findUnknownPathVar(List<String> vars, String path) {
		var int end = -1;
		var int from = 0;
		var int start = -1;
		while ((start = path.indexOf("{", from)) > -1) {
			end = path.indexOf('}', start + 1);
			if (end == -1) {

				// No closing bracket found...
				from = path.length();
			} else {
				var String name = path.substring(start + 1, end);
				if (isSimpleVariableName(name) && !vars.contains(name)) {
					return name
				}
				from = end + 1;
			}
		}
		return null
	}

	private static def boolean isSimpleVariableName(String name) {
		name.matches("[A-Za-z_$][A-Za-z0-9_$]*")
	}

	/**
	 * Returns the first "${...}" of a command message that will not render, as an issue code paired
	 * with what to tell the author, or NULL if every one of them is usable. Three different defects,
	 * so three codes: nothing closes it, no renderer understands it, or nothing supplies it.
	 */
	private static def Pair<String, String> findUnusableCommandVar(List<String> vars, String msg) {
		var int from = 0;
		var int start = -1;
		while ((start = msg.indexOf("${", from)) > -1) {
			val int end = msg.indexOf('}', start + 1);
			if (end == -1) {

				// No closing bracket. Neither renderer treats this as a variable: both leave it
				// standing, so the message quietly shows its own source.
				return COMMAND_MSG_UNCLOSED_VAR -> "The variable '" + msg.substring(start + 2)
					+ "' is not closed with '}'"
			}
			val String expr = msg.substring(start + 2, end);
			if (!isVariablePath(expr)) {
				return COMMAND_MSG_NOT_A_PATH -> "'" + expr + "' is not a plain variable or a dotted "
					+ "path. A command's message is rendered by the client as well, which has no "
					+ "expression language"
			}
			if (!vars.contains(rootOf(expr)) && rootOf(expr) != "entityIdPath") {
				return COMMAND_MSG_UNKNOWN_VAR -> "A variable with the name '" + rootOf(expr)
					+ "' is unknown"
			}
			from = end + 1;
		}
		return null
	}

	/** Whether the expression is a plain identifier or identifiers joined by dots, and nothing else. */
	private static def boolean isVariablePath(String expr) {
		expr.matches("[A-Za-z_$][A-Za-z0-9_$]*(\\.[A-Za-z_$][A-Za-z0-9_$]*)*")
	}

	/** The variable a path starts at - "provider" in "provider.id" - which is what has to exist. */
	private static def String rootOf(String expr) {
		val int dot = expr.indexOf('.')
		return if (dot == -1) expr else expr.substring(0, dot)
	}

    private static def String typeNames(List<Type> types) {
    	if (types === null) {
    		return ""
    	}
    	val StringBuilder sb = new StringBuilder();
    	for (type : types) {
    		if (sb.length > 0) {
    			sb.append(", ")
    		}
    		sb.append(type.name)
    	}
    	return sb.toString()
    }
	
    private static def List<Type> types(EList<Attribute> attributes) {
    	if (attributes === null) {
    		return Collections.emptyList();
    	}
    	val list = new ArrayList<Type>
    	for (attribute : attributes) {
    		list.add(attribute.type)
    	}
    	return list
    }

}
