/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.fuin.dsl.cqrs.cqrsDsl.AbstractElement;
import org.fuin.dsl.cqrs.cqrsDsl.AbstractEntity;
import org.fuin.dsl.cqrs.cqrsDsl.BusinessRule;
import org.fuin.dsl.cqrs.cqrsDsl.Constructor;
import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.Method;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Entity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractEntityImpl#getBusinessRules <em>Business Rules</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractEntityImpl#getConstructors <em>Constructors</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractEntityImpl#getMethods <em>Methods</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AbstractEntityImpl#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AbstractEntityImpl extends InternalTypeImpl implements AbstractEntity
{
  /**
   * The cached value of the '{@link #getBusinessRules() <em>Business Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBusinessRules()
   * @generated
   * @ordered
   */
  protected EList<BusinessRule> businessRules;

  /**
   * The cached value of the '{@link #getConstructors() <em>Constructors</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstructors()
   * @generated
   * @ordered
   */
  protected EList<Constructor> constructors;

  /**
   * The cached value of the '{@link #getMethods() <em>Methods</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethods()
   * @generated
   * @ordered
   */
  protected EList<Method> methods;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<AbstractElement> elements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.ABSTRACT_ENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BusinessRule> getBusinessRules()
  {
    if (businessRules == null)
    {
      businessRules = new EObjectContainmentEList<BusinessRule>(BusinessRule.class, this, CqrsDslPackage.ABSTRACT_ENTITY__BUSINESS_RULES);
    }
    return businessRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Constructor> getConstructors()
  {
    if (constructors == null)
    {
      constructors = new EObjectContainmentEList<Constructor>(Constructor.class, this, CqrsDslPackage.ABSTRACT_ENTITY__CONSTRUCTORS);
    }
    return constructors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Method> getMethods()
  {
    if (methods == null)
    {
      methods = new EObjectContainmentEList<Method>(Method.class, this, CqrsDslPackage.ABSTRACT_ENTITY__METHODS);
    }
    return methods;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AbstractElement> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<AbstractElement>(AbstractElement.class, this, CqrsDslPackage.ABSTRACT_ENTITY__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_ENTITY__BUSINESS_RULES:
        return ((InternalEList<?>)getBusinessRules()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.ABSTRACT_ENTITY__CONSTRUCTORS:
        return ((InternalEList<?>)getConstructors()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.ABSTRACT_ENTITY__METHODS:
        return ((InternalEList<?>)getMethods()).basicRemove(otherEnd, msgs);
      case CqrsDslPackage.ABSTRACT_ENTITY__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_ENTITY__BUSINESS_RULES:
        return getBusinessRules();
      case CqrsDslPackage.ABSTRACT_ENTITY__CONSTRUCTORS:
        return getConstructors();
      case CqrsDslPackage.ABSTRACT_ENTITY__METHODS:
        return getMethods();
      case CqrsDslPackage.ABSTRACT_ENTITY__ELEMENTS:
        return getElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_ENTITY__BUSINESS_RULES:
        getBusinessRules().clear();
        getBusinessRules().addAll((Collection<? extends BusinessRule>)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_ENTITY__CONSTRUCTORS:
        getConstructors().clear();
        getConstructors().addAll((Collection<? extends Constructor>)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_ENTITY__METHODS:
        getMethods().clear();
        getMethods().addAll((Collection<? extends Method>)newValue);
        return;
      case CqrsDslPackage.ABSTRACT_ENTITY__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends AbstractElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_ENTITY__BUSINESS_RULES:
        getBusinessRules().clear();
        return;
      case CqrsDslPackage.ABSTRACT_ENTITY__CONSTRUCTORS:
        getConstructors().clear();
        return;
      case CqrsDslPackage.ABSTRACT_ENTITY__METHODS:
        getMethods().clear();
        return;
      case CqrsDslPackage.ABSTRACT_ENTITY__ELEMENTS:
        getElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ABSTRACT_ENTITY__BUSINESS_RULES:
        return businessRules != null && !businessRules.isEmpty();
      case CqrsDslPackage.ABSTRACT_ENTITY__CONSTRUCTORS:
        return constructors != null && !constructors.isEmpty();
      case CqrsDslPackage.ABSTRACT_ENTITY__METHODS:
        return methods != null && !methods.isEmpty();
      case CqrsDslPackage.ABSTRACT_ENTITY__ELEMENTS:
        return elements != null && !elements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AbstractEntityImpl
