/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.fuin.dsl.cqrs.cqrsDsl.Attribute;
import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.DataProtectionInstance;
import org.fuin.dsl.cqrs.cqrsDsl.Invariants;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AttributeImpl#getInvariants <em>Invariants</em>}</li>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.AttributeImpl#getDataProtection <em>Data Protection</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeImpl extends VariableImpl implements Attribute
{
  /**
   * The cached value of the '{@link #getInvariants() <em>Invariants</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInvariants()
   * @generated
   * @ordered
   */
  protected Invariants invariants;

  /**
   * The cached value of the '{@link #getDataProtection() <em>Data Protection</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDataProtection()
   * @generated
   * @ordered
   */
  protected DataProtectionInstance dataProtection;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.ATTRIBUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Invariants getInvariants()
  {
    return invariants;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInvariants(Invariants newInvariants, NotificationChain msgs)
  {
    Invariants oldInvariants = invariants;
    invariants = newInvariants;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ATTRIBUTE__INVARIANTS, oldInvariants, newInvariants);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInvariants(Invariants newInvariants)
  {
    if (newInvariants != invariants)
    {
      NotificationChain msgs = null;
      if (invariants != null)
        msgs = ((InternalEObject)invariants).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ATTRIBUTE__INVARIANTS, null, msgs);
      if (newInvariants != null)
        msgs = ((InternalEObject)newInvariants).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ATTRIBUTE__INVARIANTS, null, msgs);
      msgs = basicSetInvariants(newInvariants, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ATTRIBUTE__INVARIANTS, newInvariants, newInvariants));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataProtectionInstance getDataProtection()
  {
    return dataProtection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDataProtection(DataProtectionInstance newDataProtection, NotificationChain msgs)
  {
    DataProtectionInstance oldDataProtection = dataProtection;
    dataProtection = newDataProtection;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION, oldDataProtection, newDataProtection);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDataProtection(DataProtectionInstance newDataProtection)
  {
    if (newDataProtection != dataProtection)
    {
      NotificationChain msgs = null;
      if (dataProtection != null)
        msgs = ((InternalEObject)dataProtection).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION, null, msgs);
      if (newDataProtection != null)
        msgs = ((InternalEObject)newDataProtection).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION, null, msgs);
      msgs = basicSetDataProtection(newDataProtection, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION, newDataProtection, newDataProtection));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ATTRIBUTE__INVARIANTS:
        return basicSetInvariants(null, msgs);
      case CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION:
        return basicSetDataProtection(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ATTRIBUTE__INVARIANTS:
        return getInvariants();
      case CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION:
        return getDataProtection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ATTRIBUTE__INVARIANTS:
        setInvariants((Invariants)newValue);
        return;
      case CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION:
        setDataProtection((DataProtectionInstance)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ATTRIBUTE__INVARIANTS:
        setInvariants((Invariants)null);
        return;
      case CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION:
        setDataProtection((DataProtectionInstance)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.ATTRIBUTE__INVARIANTS:
        return invariants != null;
      case CqrsDslPackage.ATTRIBUTE__DATA_PROTECTION:
        return dataProtection != null;
    }
    return super.eIsSet(featureID);
  }

} //AttributeImpl
