/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.DataProtection;
import org.fuin.dsl.cqrs.cqrsDsl.DataProtectionInstance;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Protection Instance</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.fuin.dsl.cqrs.cqrsDsl.impl.DataProtectionInstanceImpl#getPolicy <em>Policy</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataProtectionInstanceImpl extends MinimalEObjectImpl.Container implements DataProtectionInstance
{
  /**
   * The cached value of the '{@link #getPolicy() <em>Policy</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPolicy()
   * @generated
   * @ordered
   */
  protected DataProtection policy;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataProtectionInstanceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.DATA_PROTECTION_INSTANCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataProtection getPolicy()
  {
    if (policy != null && policy.eIsProxy())
    {
      InternalEObject oldPolicy = (InternalEObject)policy;
      policy = (DataProtection)eResolveProxy(oldPolicy);
      if (policy != oldPolicy)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CqrsDslPackage.DATA_PROTECTION_INSTANCE__POLICY, oldPolicy, policy));
      }
    }
    return policy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataProtection basicGetPolicy()
  {
    return policy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPolicy(DataProtection newPolicy)
  {
    DataProtection oldPolicy = policy;
    policy = newPolicy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CqrsDslPackage.DATA_PROTECTION_INSTANCE__POLICY, oldPolicy, policy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CqrsDslPackage.DATA_PROTECTION_INSTANCE__POLICY:
        if (resolve) return getPolicy();
        return basicGetPolicy();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CqrsDslPackage.DATA_PROTECTION_INSTANCE__POLICY:
        setPolicy((DataProtection)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.DATA_PROTECTION_INSTANCE__POLICY:
        setPolicy((DataProtection)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CqrsDslPackage.DATA_PROTECTION_INSTANCE__POLICY:
        return policy != null;
    }
    return super.eIsSet(featureID);
  }

} //DataProtectionInstanceImpl
