/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.EntityPathArgument;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entity Path Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EntityPathArgumentImpl extends RuleArgumentImpl implements EntityPathArgument
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntityPathArgumentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.ENTITY_PATH_ARGUMENT;
  }

} //EntityPathArgumentImpl
