/**
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.cqrsDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.fuin.dsl.cqrs.cqrsDsl.CqrsDslPackage;
import org.fuin.dsl.cqrs.cqrsDsl.RuleExpr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rule Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RuleExprImpl extends MinimalEObjectImpl.Container implements RuleExpr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RuleExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CqrsDslPackage.Literals.RULE_EXPR;
  }

} //RuleExprImpl
