/*
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCqrsDslScopeProvider extends DelegatingScopeProvider {
}
