/**
 * generated by Xtext 2.39.0
 */
package org.fuin.dsl.cqrs;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CqrsDslStandaloneSetup extends CqrsDslStandaloneSetupGenerated {
  public static void doSetup() {
    new CqrsDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
