/*
 * generated by Xtext 2.42.0
 */
package org.fuin.dsl.cqrs.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.fuin.dsl.cqrs.parser.antlr.internal.InternalCqrsDslParser;
import org.fuin.dsl.cqrs.services.CqrsDslGrammarAccess;

public class CqrsDslParser extends AbstractAntlrParser {

	@Inject
	private CqrsDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCqrsDslParser createParser(XtextTokenStream stream) {
		return new InternalCqrsDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public CqrsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CqrsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
