/*
 * generated by Xtext 2.39.0
 */
package org.fuin.dsl.cqrs.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.fuin.dsl.cqrs.CqrsDslRuntimeModule
import org.fuin.dsl.cqrs.CqrsDslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CqrsDslIdeSetup extends CqrsDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CqrsDslRuntimeModule, new CqrsDslIdeModule))
	}
	
}
